### ISSUE TITLE
Encoding issue with utf8 wihtou BOM

### ISSUE THREAD

**Issue by ssleptsov** [gruntjs/grunt-contrib-uglify#102]
Hi, 
is there any way  to solve issue in grunjs under windows that after uglify I get js files with encoding utf8 without BOM, but I need simple utf8 it's important. Any suggestions? 
Thanks

**Comment by menimaj** [comment]
Seems like grunt-contrib-uglify dependency with uglify-js does not work.
Current version of uglify-js is 2.4.22 when i do npm install grunt-contrib-uglify and getting an error of Unexpected token '?'.
If I change the dependency version to uglify-js@2.4.15 it works well.
Please change the version of uglify-js in grunt-contrib-uglify package.json

**Comment by menimaj** [comment]
Well, this was fixed in uglify-js:
https://github.com/mishoo/UglifyJS2/issues/714#issuecomment-103842822
