### ISSUE TITLE
File order

### ISSUE THREAD

**Issue by idleberg** [gruntjs/grunt-contrib-uglify#107]
I need my uglified script to maintain a certain order, so rather than working with wildcards I'm passing a list of files.

```
uglify: {
    build: {
        src: ['src/file2.js', 'src/file1.js', 'src/file3.js' ],
        dest: 'output.js'
    }
}
```

However, the order of the files is not maintained, the output is always the same no matter in which order I pass the files. Is there any way to influence this?

**Comment by brundonsmith** [comment]
@idleberg I'm having the same issue. A posted solution would be helpful.

**Comment by idleberg** [comment]
Sorry guys, that was more than two years ago and I can't remember. I have moved on to Gulp.
