### ISSUE TITLE
Copy sourcesContent from sourceMapIn, if possible

### ISSUE THREAD

**Issue by dfreedm** [gruntjs/grunt-contrib-uglify#152]
If `sourceMapIn` is supplied with `sourcesContent`, and `sourceMapIncludeSources` is true,  the supplied `sourcesContent` should be used (and reordered if necessary).

Otherwise `sourcesContent` can be full of `null` as the source files are probably not included in the grunt config `src`.

**Comment by wrongcoder** [comment]
Just copying the value over seems to work for me. This is what I'm using; sorry, I couldn't be bothered to parameterize it or do any error checking or whatever else.
```
	grunt.registerTask("fix-uglify-source-map", "Workaround for https://github.com/mishoo/UglifyJS2/issues/419",
		function () {
			var source = grunt.file.readJSON("build/app.js.map");
			var dest = grunt.file.readJSON("build/app.min.js.map");
			dest.sourcesContent = source.sourcesContent;
			grunt.file.write("build/app.min.js.map", JSON.stringify(dest));
		});
```
