### ISSUE TITLE
File Order not maintained

### ISSUE THREAD

**Issue by Yokocapolo** [gruntjs/grunt-contrib-uglify#189]
I am requesting specific files rather then using wildcards and the order is still not being maintained. It places all files located in the libs folder after the files just located in js folder. I need jQuery to remain at the top of the files for obvious reasons. Are there anyways to stop Uglify from reordering the files during concatenation?
I have tried to concat the files together first before using Uglify with no luck and I have even resorted renaming the files themselves in numerical order to see that helped! 

Here is my Gruntfile

```
uglify: {
   build: {
    src: [
            'js/libs/jquery-2.1.0.min.js',
        'js/libs/jquery-migrate.js',
        'js/fontsize.js',
        'js/general-jquery.js',
        'js/stopCloud.js'
    ],
    dest: 'js/build/js-min.js'
    }
}
```

**Comment by PokemonAshLovesMyTurkeyAndILikeYouTwo** [comment]
@Yokocapolo  Thank you!! I was having the same exact issue and was wondering why the hell `uglify` was putting my functions at the top, especially after I concatenated the files.. lol

**Comment by pythdasch** [comment]
I'm still having this issue, and adding this compress: hoist_funs doesn't help.

I'm on version : 
    "grunt-contrib-uglify": "^2.3.0",
