### ISSUE TITLE
Non-ASCII characters for object keys are not wrapped with quotes

### ISSUE THREAD

**Issue by grevory** [gruntjs/grunt-contrib-uglify#205]
There is a commit in the main UglifyJS2 repo that resolves this issue.

https://github.com/mishoo/UglifyJS2/commit/8fbe20001215887275b3cf053be675ebdbf331a9

**Comment by XhmikosR** [comment]
@jmeas: this is included in 2.4.14 and we reference `^2.4.0`. So, I guess we should close this.

**Comment by avdg** [comment]
Please reopen or open a new issue if this issue is still occurring.
