### ISSUE TITLE
PreserveComments additional option

### ISSUE THREAD

**Issue by SamvelRaja** [gruntjs/grunt-contrib-uglify#214]
As mention in issue #213 the option for preserve comments 
function(node,comments){return true|false} is not working properly. Since we are setting the comments option for UglifyJs directly to the 'function()' provided.  

```js
   ...else if (_.isFunction(options.preserveComments)) {
        // support custom functions passed in
        outputOptions.comments = options.preserveComments;
      }....
 ```
A valid regex too can be an option since the UglifyJs Comments option also accepts a valid regex for preserving the comments or license to be preserved.  Kindly check into it.

**Comment by davidparsson** [comment]
I can confirm that UglifyJS does not handle the case when the provided `outputOptions.comments` is a function. When it's a function, the default function is used.

See the [source code](https://github.com/mishoo/UglifyJS2/blob/d2dda34b2a8de310f26a26e58ed28275ba5ecc7f/bin/uglifyjs#L228).

**Comment by SamvelRaja** [comment]
@davidparsson  :+1:  gotcha

**Comment by SamvelRaja** [comment]
I wonder why we are putting efforts [here](https://github.com/gruntjs/grunt-contrib-uglify/blob/master/tasks/lib/uglify.js#L200) instead of just passing the option value for preserver comments to UglifyJS just like we passing [here](https://github.com/gruntjs/grunt-contrib-uglify/blob/master/tasks/lib/uglify.js#L256)

**Comment by SamvelRaja** [comment]
Added the changes her https://github.com/gruntjs/grunt-contrib-uglify/pull/338

**Comment by avdg** [comment]
Is this still an issue?

**Comment by SamvelRaja** [comment]
No we can close this one.
