### ISSUE TITLE
Can't get mangle-toplevel to work

### ISSUE THREAD

**Issue by mattslocum** [gruntjs/grunt-contrib-uglify#216]
I'm trying to write a JS library, and I have variables on 'this' that I want mangled. I understand that mangle-toplevel is not enabled by default because often times people want properties to be accessible directly. I have getter/setter methods that are supposed to be used instead so I would like to compress these variables as much as possible.

For example:

```
    var MyLibrary = function(strField) {
        if (strField) {
            this.strField = strField;
            this.bRootField = false;
        } else {
            this.bRootField = true;
        }
        this.aFields = [];
        this.iLimit = 0;
        return this;
    };
    MyLibrary.prototype.getName = function() {
        return this.strField;
    };
```

I would like this.strField, this.bRootField, this.aFields, this.iLimit to be mangled. Is this feature possible with grunt-contrib-uglify?

**Comment by Fizzleban** [comment]
I have also tried to mangle the top level, and it is not working.

**Comment by caimen** [comment]
I'm trying to get this to work as well with no luck.  I swear I had it working before too.

**Comment by alexlamsl** [comment]
Those are properties, so you would want to use:
```js
options: {
    mangle: {
        properties: true
    }
}
```
