### ISSUE TITLE
expression option strips quotes on JSON

### ISSUE THREAD

**Issue by gh-amistry** [gruntjs/grunt-contrib-uglify#218]
The new 'expression' option is great for processing JSON files, however it strips quotes from the keys, which invalidates the JSON (ie. it won't pass in JSONLint).

For example, a target json file called config.json might look like this:
{
  "version" : "1",
  "channel" : "web"
}

The task would be configured as:
config_beautify: {
  options : {
    expression: true,
    beautify: true
  }
}

The output is missing quotes around the keys, making it invalid JSON
{
  version : "1",
  channel : "web"
}

**Comment by avdg** [comment]
Is this still an issue? Also, uglifyjs might be changed a lot by now

**Comment by gh-amistry** [comment]
@avdg thanks for following up. It's no longer an issue, at least for me. Closing.
