### ISSUE TITLE
Line separator between input files

### ISSUE THREAD

**Issue by hajiz** [gruntjs/grunt-contrib-uglify#227]
There is no way to uglify and concat files with a separator between the files in the output. grunt-contrib-concat provides a 'separator' option, but the same is missing from grunt uglify.

The usage for such an option is to separate minified version of files with a new line to make it easy to find cause of javascript errors based on line number in the minified version.

**Comment by alexlamsl** [comment]
Code sections will move across boundaries of input files when they are compressed by `uglify-js`, so there is no meaningful way to insert a line break anywhere:
```js
// a.js
function a() {
  return 1;
}
console.log(a());
// b.js
function b() {
  return 2;
}
console.log(b());
```
... will become:
```js
function a() {
  return 1;
}
function b() {
  return 2;
}
console.log(a());
console.log(b());
```
