### ISSUE TITLE
How to uglify all .js files within a directory?

### ISSUE THREAD

**Issue by mmatzanke** [gruntjs/grunt-contrib-uglify#23]
Hey I'm new with this task,

I would like to know how to uglify all *.js files within a directory via task description object within the grunt file? Probably i do not understand it like the way i should ;-). 

greetz Martin

**Comment by cyberience** [comment]
This may help you. using bash script to handle the multi file issue.
find . -type f -exec ls "{}" \; |  grep .js | xargs -n 1 java -jar yuicompressor-2.4.8.jar
just change the yuicompressor part to your fav compressor, find will hunt the files and pass them 1 by 1 to xarg filtering only js files through grep. and xarg makes the file an imput paramet for the compressor.

**Comment by omidraha** [comment]
I use this:
```
uglify: {
	dev: {
		options: {
			mangle: false
		},
		files: [{
			expand: true,
			src: 'dist/assets/js/*.js',
			dest: 'dist/assets',
			cwd: '.',
			rename: function (dst, src) {
				// To keep src js files and make new files as *.min.js :
				// return dst + '/' + src.replace('.js', '.min.js');
				// Or to override to src :
				return src;
			}
		}]
	}
},
```

**Comment by robots4life** [comment]
```
      all_vendor_js: {
        files: [
          {
            expand: true,
            cwd: "resources/vendor/js/",
            src: ["*.js", "!*.min.js"],
            dest: "resources/vendor/js/min",
            ext: ".min.js"
          }
        ]
      },
```
Original files in resources/vendor/js folder.
Minified files in resources/vendor/js/min folder and .min.js file ending.
