### ISSUE TITLE
grunt-contrib-uglify hangs when it tries to uglify a minified file

### ISSUE THREAD

**Issue by nareshbhatia** [gruntjs/grunt-contrib-uglify#233]
One of the files in my project is a minified 3rd party library. When grunt-contrib-uglify tries to uglify it, the build hangs completely - the grunt prompt never comes back. I am trying to figure out if this is a bug or uglify is not intended to uglify an already minified file.

**Comment by XhmikosR** [comment]
Check out globs and `['foo.js', '!bar.js']`.

**Comment by dannysouza16** [comment]
The exclamtion prefix doesnt work, He exclude the min file of the output file.

There is a solutions? Anyone?

**Comment by avdg** [comment]
Is this still an issue in the latest uglify releases?

**Comment by ivnmaksimovic** [comment]
I had the same issue before and I had to use just unminified files. Now I am running grunt-contrib-uglify 2.0.0 and my vendor sources are mix of unminified and minified files. 
No problems anymore!
