### ISSUE TITLE
No more UI without `--verbose`?

### ISSUE THREAD

**Issue by JamesMGreene** [gruntjs/grunt-contrib-uglify#249]
PR #229 reduced verbosity by so much than a normal use of this plugin no longer produces any UI feedback unless the `--verbose` flag is set.  This is confusing and doesn't offer any worthwhile benefit that I can see.

**Running normally:**

``` shell
Running "uglify:dist" (uglify) task

```

**Running with `--verbose`:**

``` shell
Running "uglify" task

Running "uglify:dist" (uglify) task
Verifying property uglify.dist exists in config...OK
Files: dist/document.currentScript.js -> dist/document.currentScript.min.js
Options: banner="", footer="", compress={"warnings":false}, mangle={}, beautify=false, report="min", expression=false, preserveComments="some"
Minifying with UglifyJS...Reading dist/document.currentScript.js...OK
OK
Writing dist/document.currentScript.min.js...OK
File dist/document.currentScript.min.js created: 4.93 kB → 2.06 kB

```

Mac OS X Mavericks (10.9), Node v0.10.28, grunt-cli@0.1.13, grunt@0.4.5, grunt-contrib-uglify@0.5.1

**Comment by joaovieira** [comment]
:+1:  what @JamesMGreene said: having the reports back would be nice.

**Comment by prionkor** [comment]
+1 The compression report should be shown like `cssMin`
