### ISSUE TITLE
Setting 'compress' option to 'false' still results in minified output

### ISSUE THREAD

**Issue by hal-gh** [gruntjs/grunt-contrib-uglify#257]
My issue is exactly the same as #65. I believe it was closed with a workaround rather than a fix, and hence there is no way to prevent mangle/compression.

My ultimate goal is to strip all comments from `bundle.min.js` using this config:

```javascript
removeComments: {
  options: {
    compress: false,
    mangle: false,
    preserveComments: false
  },
  src: [
    './path/to/bundle.min.js'
  ],
  dest: './path/to/bundle.min.js'
}
```

**Comment by FrankFan** [comment]
```javascript
// 是否压缩代码
output: {
    beautify: false
}
```

**Comment by MichaelJCole** [comment]
See [this issue in UglifyJS](https://github.com/mishoo/UglifyJS2/issues/696)

**Comment by MichaelJCole** [comment]
Hey, what was the result of this?  Uglify is breaking my AngularJS code.  

'Error: [$compile:nonassign] Expression '' used with directive 'graphTree' is non-assignable!'

I'd like to turn if off, but it's built into the Angular-Fullstack toolchain, so I can't just remove the grunt task and have it work.

How do I turn off mangling?
