### ISSUE TITLE
Suppress warnings?

### ISSUE THREAD

**Issue by Izzmo** [gruntjs/grunt-contrib-uglify#258]
Is there a way to suppress warnings from output like the unused variables messages?

It is causing my builds to fail. I don't want to use the --force option because it causes all my packages to force.

**Comment by monolithed** [comment]
Try  to use `drop_console` option, or see my issue https://github.com/gruntjs/grunt-contrib-uglify/issues/291

**Comment by Izzmo** [comment]
@monolithed that's interesting, thanks for the update!
