### ISSUE TITLE
Source Map is generated, loaded by browser (HTTP 200), but does not work.

### ISSUE THREAD

**Issue by vgrinko** [gruntjs/grunt-contrib-uglify#266]
Hi everyone,

I am experiencing weird issue with uglify/sourceMap feature.
Generally, source map is generated, loaded by browser (HTTP 200), but does not work (in the "Sources" tab of Chrome, everything still looks minified/uglified). At the same time other sourcemaps (on another project) are working well.

Here is my grunt uglify configuration:  

``` javascript
    bootstrap: {
        options: {
            sourceMap: true
        },
        files: {
            'build/bootstraps/bootstrap.js': ['build/bootstraps/bootstrap.js']
        }
    }
```

what it does is uglify/minify+sourcemap of 1 file (which is located at build/bootstraps/bootstrap.js).
Yes, it uglifies itself (since it is result of multi-step process).
I tried to separate, same result.

Here is what generated:  
_bootstrap.js_: 

``` javascript
    !function(a,b){"use strict";var c=.......
    //# sourceMappingURL=bootstrap.js.map
```

_bootstrap.js.map_:  

``` javascript
    {"version":3,"file":"bootstrap.js","sources":["bootstrap.js"],"names":["global","manifest","Bootstrap","init","require","$",....
    "mappings": "CAAA,SAAWA,EAAQC,GACf,YAGA.....
```

Can you please suggest any direction where the issue can be?

**Comment by atav32** [comment]
Do your maps throw an error when parsed by the BASE64 VLQ CODEC http://murzwin.com/base64vlq.html

`Invalid input: Unexpected token v`

-----

I've also tried serving `.map` files as `application/json` instead of the nginx default (`application/octet-stream`), but that didn't seem to change anything

**Comment by atav32** [comment]
Or is it related to this issue https://github.com/gruntjs/grunt-contrib-uglify/issues/270?

**Comment by SamVerschueren** [comment]
Experiencing the same issue

```
Invalid input: Unexpected token v
```

**Comment by smonev** [comment]
Same here:
> Invalid input: Unexpected token v

**Comment by elsigh** [comment]
Same here:
Invalid input: Unexpected token v

But I'm using webpack, so this might be a red herring?

**Comment by smonev** [comment]
jQuery source map also produces the same error: ```Invalid input: Unexpected token v``` so I am exactly sure what we can make of the error.

By the way, my problems were solved by upgrading all my npm modules to the latest versions. So I am not sure what exactly the problem was.

**Comment by light24bulbs** [comment]
has anyone figured this out?

**Comment by alexlamsl** [comment]
There have been fixes to source-map on `uglify-js@3`, so this may already be addressed.

Please report to https://github.com/mishoo/UglifyJS2/issues with reproducible test case if this is still an issue.
