### ISSUE TITLE
Source Map path is incorrect

### ISSUE THREAD

**Issue by JasperH8g** [gruntjs/grunt-contrib-uglify#270]
When creating source maps without any other configuration, the following (as expected) would be appended to the js-file: 

``` js
//# sourceMappingURL=app.map
```

But actually, the generated source map has `app.js.map` as its filename, causing dev-tools to not find it. Manually setting the name via `sourceMapName` fixes this for me, but it doesn't seem to be correct default behaviour.

**Comment by monolithed** [comment]
+1
