### ISSUE TITLE
customize drop_console 

### ISSUE THREAD

**Issue by AliMD** [gruntjs/grunt-contrib-uglify#274]
I want to customize drop_console option to keep console.error and console.warning.
Is it possible or any hack/tricks ?
Thank you in dvance

**Comment by shinnn** [comment]
This is an issue with [the upstream project](https://github.com/mishoo/UglifyJS2). Use [mishoo/UglifyJS2 issue tracker](https://github.com/mishoo/UglifyJS2/issues).
