### ISSUE TITLE
Uglification fails with asm.js

### ISSUE THREAD

**Issue by tcipierre** [gruntjs/grunt-contrib-uglify#285]
Hi everyone,

First of all, thanks for the tremendous work on Grunt, which is so convenient to build/test with Bower and Yo. I hope I am reporting my issue on the good Grunt repository.

I have some troubles working with audio applications, which are very demanding and need asm.js optimisation. *Grunt --serve* works pretty fine, but as long as I try to render my project (which includes some asm-js), I have to run *--force* to bypass jshint errors, and uglify fails, not producing any app.js file at all. Here is the last console log :

> Warning: Uglification failed.
> Unexpected token name «of», expected punc «;». 
> Line 2686 in .tmp/concat/scripts/app.js
> Used --force, continuing.
> Warning: Cannot read property 'min' of undefined Used --force, continuing.

Any idea or plan in the future to solve this ?
Thanks for reading and all the best.

**Comment by sindresorhus** [comment]
Uglify failed to parse your JS. You might have some invalid JS or there might be a bug with uglify.

Either way, should be posted here: https://github.com/mishoo/UglifyJS2 along with the code from `Line 2686 in .tmp/concat/scripts/app.js`.

**Comment by tcipierre** [comment]
Thanks a lot for your help sindresorhus, I'll do.
