### ISSUE TITLE
Add option to preserve quote style

### ISSUE THREAD

**Issue by aendrew** [gruntjs/grunt-contrib-uglify#293]
I do a bunch of weird stuff with JSON in one of my projects, with lots of weird escaping/unescaping. I've had to disable `grunt-contrib-uglify` because it changes all of my quotes around and breaks everything.

HOWEVER, [this recent change to UglifyJS](https://github.com/mishoo/UglifyJS2/commit/fbbaa42ee55a7f753f7cab9b1a905ccf73cf26d5) grants the ability to preserve quotes. It would be *phenomenal* to have it as an option in `grunt-contrib-uglify`.

**Comment by sindresorhus** [comment]
PR welcome :)

**Comment by aendrew** [comment]
Happy to, though they haven't put it in a release yet — I've mostly written the PR but will submit it once they do a new release.

Also, haven't really PR'd a grunt plugin before — am I correct in thinking all I need to do (beyond adding tests/documentation/etc) is add a line `this.options`?

**Comment by 190n** [comment]
+1 million

**Comment by aendrew** [comment]
Lulz, dat commit log... :sweat_smile:
