### ISSUE TITLE
Add option to remove console.logs from files

### ISSUE THREAD

**Issue by augbog** [gruntjs/grunt-contrib-uglify#297]
Is it possible to add an option that will automatically remove all `console.log` in files? I feel this would be a handy feature to have when minifying/uglifying JavaScript files.

**Comment by vladikoff** [comment]
https://github.com/gruntjs/grunt-contrib-uglify#turn-off-console-warnings

**Comment by augbog** [comment]
My bad. Thanks for the quick close.
