### ISSUE TITLE
TypeError: Cannot assign to read only property 'warnings' of true

### ISSUE THREAD

**Issue by rauberdaniel** [gruntjs/grunt-contrib-uglify#298]
I recently updated to node 0.12.0 and right now I’m getting the following error with grunt-contrib-uglify version 0.7.0:

```
Running "uglify:min" (uglify) task
[TypeError: Cannot assign to read only property 'warnings' of true]
>> Uglifying source static/js/main.js failed.
Warning: Uglification failed.
Cannot assign to read only property 'warnings' of true.
 Use --force to continue.

Aborted due to warnings.
```

Happens with any .js file, so it seems to be a bug either with nodejs v0.12.0 or with this uglify task. Any ideas?

**Comment by rauberdaniel** [comment]
I guess I found the reason: Having set the option `compress` to `true` instead of `{}` (which is allowed by documentation) causes the issue.

**Comment by pyalxx** [comment]
+1! You saved my day, thanks!

**Comment by XhmikosR** [comment]
Duplicate of #287.

**Comment by NorikDavtian** [comment]
:+1: @rauberdaniel tnxx

**Comment by ahmednuaman** [comment]
So I had this problem too, but it was fixed by running `git clean -xdf` and `npm install` again.

**Comment by 4aficiona2** [comment]
replacing `true` with `{}` worked for me too. Thanks @rauberdaniel

**Comment by 2013gang** [comment]
+1

**Comment by willthemoor** [comment]
Thank you @rauberdaniel!

**Comment by Deanzie** [comment]
+1

**Comment by amccarthyMatchbook** [comment]
+1
