### ISSUE TITLE
Issues minifying lodash 3.x

### ISSUE THREAD

**Issue by niemyjski** [gruntjs/grunt-contrib-uglify#299]
Has anyone else been running into issues trying to minify lodash 3.x? I'm getting _ is undefined errors.

**Comment by niemyjski** [comment]
Seems to be an issue as referenced here: https://github.com/lodash/lodash/issues/900#issuecomment-74587039

**Comment by XhmikosR** [comment]
It's an upstream issue.

**Comment by niemyjski** [comment]
Thanks
