### ISSUE TITLE
fail task when a source file is missing?

### ISSUE THREAD

**Issue by cowboy** [gruntjs/grunt-contrib-uglify#3]
People complain when we don't fail tasks on missing files. This kills the whole task if a file is missing:

https://github.com/gruntjs/grunt-contrib-uglify/blob/6543c160c5c8df22d164b2ec59d7e0292ddf2fcc/tasks/uglify.js#L28-L39

Should the task fail? Should it just log that a file was missing and continue?

**Comment by MaximRouiller** [comment]
Just had that issue. 

Had something named `Scripts/my.datepicker.js` included in the uglify list.

File is named `Scripts/my-datepicker.js`. No warning. No failure. Nothing in verbose.

What about... If there's a non-wildcard path, we ensure that file at least generate a warning of a "FAIL" in the verbose log? Just my 2 cents.

**Comment by nicolasxu** [comment]
I need the task to FAIL if the file (without wild character) I specify doesn't exist!!!

**Comment by cantuket** [comment]
This is kind of insane....

A 4yr old issue, closed and re-opend 3 times and still no straight forward answer for something I'd expect to be the first option listed in the documentation. Please, how do you log missing files?

I just spent over an hour sifting through my Grunt configuration!!!

```
grunt.log.warn = grunt.warn;
```
...not working 

```
options: {
		        sourceMap: true,
		        debug:true,
		        nonull: true
		      },
```
...not working

**Comment by chill117** [comment]
In my opinion `nonull: true` should cause the task to fail (not just log and continue).

**Comment by MaximRouiller** [comment]
Hey, it's javascript. It should fail without any warning and no logs and be leaving you wondering what the hell happened for 3 hours.

How else are we going to justify our salaries? 

Jokes aside... re-opening this issue would be a first step.

**Comment by bgmat** [comment]
Hey, this is kind of old, but it might be useful to someone ...
The `nonull: true` works (outputs an warning) if the files are written like this:
```
files: [
	{
		src: ['a.js', 'b.js', ...],
		dest: 'c.js',
		nonull: true
	}
]
```
Then, you can find [here](https://stackoverflow.com/questions/27721272/is-there-a-way-to-cause-a-grunt-plugin-to-fail-if-input-files-are-missing) how to stop on this warning.
