### ISSUE TITLE
Node.js 0.12 `report: 'gzip'` error

### ISSUE THREAD

**Issue by robwalch** [gruntjs/grunt-contrib-uglify#302]
Fails with warning/error `Warning: Cannot assign to read only property 'subarray'` when the `report: 'gzip'` is present. Came across #287 and modified the compress option, but removing the report option is the only thing that worked.

**Comment by timotgl** [comment]
Can confirm that removing the report option also worked for me.

**Comment by XhmikosR** [comment]
Does this happen with the latest version?

**Comment by robwalch** [comment]
@XhmikosR I'm using grunt 0.4.5 with grunt-contrib-uglify 0.8.0 with `report: 'gzip'`. It works, but I only see the report details with verbose enabled.

```sh
grunt uglify
```
```
Running "uglify:player" (uglify) task
>> 1 file created.
```

```sh
grunt uglify --verbose
```
```
Running "uglify:player" (uglify) task
Verifying property uglify.player exists in config...OK
Files: bin-debug/jwplayer.js -> bin-release/jwplayer.js
Options: banner="", footer="", compress={"booleans":true,"cascade":true,"conditionals":true,"dead_code":true,"drop_console":true,"evaluate":true,"if_return":true,"join_vars":true,"pure_getters":true,"sequences":true,"unused":true,"warnings":false}, mangle, beautify=false, report="gzip", expression=false, maxLineLen=32000, ASCIIOnly=false, screwIE8=false
Minifying with UglifyJS...Reading bin-debug/jwplayer.js...OK
OK
Writing bin-release/jwplayer.js...OK
File bin-release/jwplayer.js created: 609.97 kB → 214.36 kB → 76.35 kB (gzip)
>> 1 file created.
```

**Comment by XhmikosR** [comment]
That is expected although personally I  don't like this approach.

**Comment by XhmikosR** [comment]
Feel free to open a new issue about moving the size report to normal output.
