### ISSUE TITLE
"use strict" BUG on Safari

### ISSUE THREAD

**Issue by herlon214** [gruntjs/grunt-contrib-uglify#305]
Hi guys, I'm having a trouble using Safari, and I solved removing the "use strict" on the deployed file.
Why is this happening?

Thanks in advance, and sorry for the noob question.

**Comment by UltCombo** [comment]
Issues with the output should be reported in the [uglify repository](https://github.com/gniavaj/uglify2).

And you're most likely concatenating files with `use strict;` in the top-most scope with sloppy files.
