### ISSUE TITLE
>= 0.6.x doesn't work with jit-grunt anymore (?)

### ISSUE THREAD

**Issue by pateketrueke** [gruntjs/grunt-contrib-uglify#307]
I'm not sure if the issue is from `jit-grunt` or `grunt-contrib-uglify` itself but when I switch to `grunt-contrib-uglify@0.5.1` the issue was gone.

**Comment by sindresorhus** [comment]
No idea how `jit-grunt` works, but any compatibility issue should be opened there and not here.
