### ISSUE TITLE
Is it possible just to rename and copy a file without minifying?

### ISSUE THREAD

**Issue by developer1998** [gruntjs/grunt-contrib-uglify#308]
It is working well for the files that I want to minify. 
However, there are some script files that I just want to rename and copy without minifying. Is there a way to do this within this plugin?
Thank you.

**Comment by gregor-w** [comment]
Use grunt-contrib-copy

**Comment by arthurvr** [comment]
https://github.com/gruntjs/grunt-contrib-copy is what you need.

**Comment by arthurvr** [comment]
And @gregor-w was just a few seconds faster :D

**Comment by developer1998** [comment]
Thank you.
