### ISSUE TITLE
AngularJS - uglify angular.module

### ISSUE THREAD

**Issue by nitulkukadia** [gruntjs/grunt-contrib-uglify#320]
angular.module('myApplication').factory('myService', [function() {
        return {
            name: 'name'
        };
    }]);

When I tried to inject above service in my controller.

    myApplication.controller('myController', [ 'myService',  function(myService) {}]);

It gives me below error:

Error: $injector:unpr
Unknown Provider
Unknown provider: myServiceProvider <- myService <- myController

**Comment by sindresorhus** [comment]
https://github.com/olov/ng-annotate

**Comment by nitulk** [comment]
@sindresorhus  it is not working.

It has changed my file to as below (removed array brackets):

angular.module('myApplication').factory('myService', function() {
    return {
        name: 'name'
    };
});

but after uglifying it still gives me same error.

**Comment by nitulkukadia** [comment]
@sindresorhus it is not working.

It has changed my file to as below (removed array brackets):

angular.module('myApplication').factory('myService', function() {
return {
name: 'name'
};
});

but after uglifying it still gives me same error.

**Comment by sindresorhus** [comment]
This is not the right place for support questions. Use StackOverflow.

**Comment by nitulkukadia** [comment]
Thanks.
