### ISSUE TITLE
ascii_only property for beautify doesn't work

### ISSUE THREAD

**Issue by XEuRoMAN** [gruntjs/grunt-contrib-uglify#322]
I had problem that my unicoded values was converted to ASCII symbols during uglify task, so, I was finding for solution and there was a lot of examples that I should use property like this in my uglify task:
```js
options : {
    beautify : {
        ascii_only: true
    }
}
```
here: https://github.com/gruntjs/grunt-contrib-uglify/issues/31#issuecomment-14320863
here: https://github.com/gruntjs/grunt-contrib-uglify/pull/139#issuecomment-32795789

but this solution doesn't work. So, I spent some time (because I really need that feature) to find what's wrong and found a mistake.

Simply, this property is not expecting inside the code.
There is simple workaround:
```js
options : {
    ASCIIOnly: true
}
```

I'm making pull request, so merge it if you think it's worth to save so time to other guys :)

**Comment by brendonco** [comment]
Hi,
It seems ASCIIOnly : true doesnt work.  I have a unicode string in js e.g. \u0074\u0065\u0073\u0074 but after minified, the unicode character are converted back to a normal string.

 uglify: {
      options: {
        // banner: '/*! <%= pkg.name %> <%= grunt.template.today("yyyy-mm-dd") %> */\n'
        ASCIIOnly: true
      },
      build: {
        src: 'dist/www/js/<%= pkg.name %>.js',
        dest: 'dist/www/js/<%= pkg.name %>.min.js'
      }
    },

**Comment by justas-adtargetme** [comment]
Hi, @brendonco 

I'm using `"grunt-contrib-uglify": "0.9.1"`

and my uglify properties looks like this:

```js
uglify: {
    options: {
        report: 'min'
    },
    'all': {
        options: {
            ASCIIOnly: true
        },
        files: {
            'destination/js.min.js': ['destination/js.js'],
            'destination/js2.min.js': ['destination/js2.js']
        }
    }
},
```

**Comment by XEuRoMAN** [comment]
Hi, @brendonco 

I'm using `"grunt-contrib-uglify": "0.9.1"`

and my uglify properties looks like this:

```js
uglify: {
    options: {
        report: 'min'
    },
    'all': {
        options: {
            ASCIIOnly: true
        },
        files: {
            'destination/js.min.js': ['destination/js.js'],
            'destination/js2.min.js': ['destination/js2.js']
        }
    }
},
```

**Comment by brendonco** [comment]
Hi @XEuRoMAN ,

I'm using latest "grunt-contrib-uglify": "^0.9.1" and below is the package.json for uglify.  I still getting my unicode transform back to visible string.

```
uglify: {
      options: {
        report: 'min'
      },
      build: {
        options: {
            ASCIIOnly: true
        },
        files: {
          'dist/www/js/<%= pkg.name %>.min.js' : ['dist/www/js/<%= pkg.name %>.js']
        }
      }
    }
```

**Comment by XEuRoMAN** [comment]
Then I only could guess what could be wrong...

Why do you say that there is your `package.json` content? As I know, package.json are used for npm to install packages and `Gruntfile` for all grunt tasks...

Anyway, try to debug `grunt-contrib-uglify` module. See how looks `options` object inside `minifiy` function.

**Comment by brendonco** [comment]
sorry I mean above script is my Gruntfile.js not package.json. let me debug the grunt-contrib-uglify and see what I can find.

**Comment by avdg** [comment]
@brendonco Is the problem solved? If not, do you have an example file?

**Comment by XhmikosR** [comment]
I'm gonna make a branch for this since I think I have already isolated the problem.
