### ISSUE TITLE
Mangled local variables not getting 'mapped' back properly in chrome or firefox

### ISSUE THREAD

**Issue by paulbennet** [gruntjs/grunt-contrib-uglify#325]
The local variables names gets mangled to shorter names (a,b,c,d...) when uglifying with "sourcemaps". But when loaded in browser (chrome and firefox) the shortened names doesn't get mapped back to the variables names in the original source. This happens when the sources are "included" and also when the original source files are used (both cases). This is causing much pain when we have to debug in production code. Please fix this soon.

http://stackoverflow.com/questions/29718639/local-variable-name-mapping-does-not-work-in-dev-tools-when-mangletrue-is-set-i

Above is my SO question related to this.

**Comment by saravananceg** [comment]
+1 for this issue. Please can you advise on this issue. Debugging is very painful as paul mentioned.

**Comment by mukundmurrali** [comment]
Any update on this issue ?

**Comment by jeroenheijmans** [comment]
An answer came in on that SO question, mentioning an [Issue reported for Chromium](https://code.google.com/p/chromium/issues/detail?id=327092), also reporting that mapping back to the variable names isn't working. It seems claimed there that this is a problem with the sourcemappings spec.

**Comment by larpo** [comment]
This was a browser issue. To my surprise, I noticed today that the name mapping support had started working on Chrome Canary. After short digging found corresponding chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=327092
