### ISSUE TITLE
uglify transforms multi-line string return wrongly

### ISSUE THREAD

**Issue by Rouby** [gruntjs/grunt-contrib-uglify#326]
From the angular-material repository, options for uglify

    compress: false, 
    sourceMap: true.

This part

    template: function (element, attr) {
        //-- grab the original HTML for custom transclusion before Angular attempts to parse it
        //-- the HTML is being stored on the attr object so that it is available to postLink
        attr.$mdAutocompleteTemplate = element.html();
        //-- return the replacement template, which will wipe out the original HTML
        return '\
          <md-autocomplete-wrap role="listbox">\
            <md-input-container ng-if="floatingLabel">\
              <label>{{floatingLabel}}</label>\
              <input type="text"\
                  id="fl-input-{{$mdAutocompleteCtrl.id}}"\
                  name="{{name}}"\
                  autocomplete="off"\
                  ng-disabled="isDisabled"\
                  ng-model="$mdAutocompleteCtrl.scope.searchText"\
                  ng-keydown="$mdAutocompleteCtrl.keydown($event)"\
                  ng-blur="$mdAutocompleteCtrl.blur()"\
                  ng-focus="$mdAutocompleteCtrl.focus()"\
                  aria-owns="ul-{{$mdAutocompleteCtrl.id}}"\
                  aria-label="{{floatingLabel}}"\
                  aria-autocomplete="list"\
                  aria-haspopup="true"\
                  aria-activedescendant=""\
                  aria-expanded="{{!$mdAutocompleteCtrl.hidden}}"/>\
                \
            </md-input-container>\
            <input type="text"\
                id="input-{{$mdAutocompleteCtrl.id}}"\
                name="{{name}}"\
                ng-if="!floatingLabel"\
                autocomplete="off"\
                ng-disabled="isDisabled"\
                ng-model="$mdAutocompleteCtrl.scope.searchText"\
                ng-keydown="$mdAutocompleteCtrl.keydown($event)"\
                ng-blur="$mdAutocompleteCtrl.blur()"\
                ng-focus="$mdAutocompleteCtrl.focus()"\
                placeholder="{{placeholder}}"\
                aria-owns="ul-{{$mdAutocompleteCtrl.id}}"\
                aria-label="{{placeholder}}"\
                aria-autocomplete="list"\
                aria-haspopup="true"\
                aria-activedescendant=""\
                aria-expanded="{{!$mdAutocompleteCtrl.hidden}}"/>\
            <button\
                type="button"\
                tabindex="-1"\
                ng-if="$mdAutocompleteCtrl.scope.searchText && !isDisabled"\
                ng-click="$mdAutocompleteCtrl.clear()">\
              <md-icon md-svg-icon="cancel"></md-icon>\
              <span class="md-visually-hidden">Clear</span>\
            </button>\
            <md-progress-linear\
                ng-if="$mdAutocompleteCtrl.loading"\
                md-mode="indeterminate"></md-progress-linear>\
            <ul role="presentation"\
                class="md-autocomplete-suggestions {{menuClass || \'\'}}"\
                id="ul-{{$mdAutocompleteCtrl.id}}"\
                ng-mouseenter="$mdAutocompleteCtrl.listEnter()"\
                ng-mouseleave="$mdAutocompleteCtrl.listLeave()"\
                ng-mouseup="$mdAutocompleteCtrl.mouseUp()">\
              <li ng-repeat="(index, item) in $mdAutocompleteCtrl.matches"\
                  ng-class="{ selected: index === $mdAutocompleteCtrl.index }"\
                  ng-hide="$mdAutocompleteCtrl.hidden"\
                  ng-click="$mdAutocompleteCtrl.select(index)"\
                  md-autocomplete-list-item-template="contents"\
                  md-autocomplete-list-item="$mdAutocompleteCtrl.itemName">\
              </li>\
            </ul>\
          </md-autocomplete-wrap>\
          <aria-status\
              class="md-visually-hidden"\
              role="status"\
              aria-live="assertive">\
            <p ng-repeat="message in $mdAutocompleteCtrl.messages">{{message.display}}</p>\
          </aria-status>';
      }

gets transformed into

    template:function(a,b){b.$mdAutocompleteTemplate=a.html();return;'\r\n          <md-autocomplete-wrap role="listbox" ...............................

Notice the semicolon right before the string literal.

**Comment by Rouby** [comment]
If I encapsulate the string-literal (before transformation) with brackets it gets transformed correctly.

    return ('\
        .......\
        ';

**Comment by sindresorhus** [comment]
Any issue with the output should be posted on the Uglify issue tracker.

https://github.com/mishoo/UglifyJS2/issues/new
