### ISSUE TITLE
Cannot set sourceMappingURL to be absolute path

### ISSUE THREAD

**Issue by waltfy** [gruntjs/grunt-contrib-uglify#332]
From the documentation:

> `sourceMappingURL` - This is calculated automatically now `sourceMapPrefix` - No longer necessary for the above reason

Does the plugin provide any other way of mutating the `sourceMappingURL`?

**Comment by gauntface** [comment]
I'm actually hitting similar issues with this. Any tips?

**Comment by waltfy** [comment]
@gauntface I am currently using @marlun78's branch of this project. Maybe it'll help?

https://github.com/gruntjs/grunt-contrib-uglify/pull/331

**Comment by vladikoff** [comment]
Merged via a PR related to #331
