### ISSUE TITLE
"WARN: Side effects in initialization of unused variable ..." to strict ?

### ISSUE THREAD

**Issue by redaktor** [gruntjs/grunt-contrib-uglify#335]
Hey,
while working on
https://github.com/spencermountain/nlp_compromise/issues/42
i am getting
```WARN: Side effects in initialization of unused variable foo```
But in fact I am using foo
- in a unified module with window.foo

Let us say I have an object 
```var m = { foo: 'bar' };```
When used with node 
m.foo will be module foo
When used in the browser
m would be window and m.foo = window.foo and so foo is used ...

**Comment by sindresorhus** [comment]
This is just a plugin for Uglify. Open an issue here instead: https://github.com/mishoo/UglifyJS2/issues/new
