### ISSUE TITLE
Unexpected token: punc (:)

### ISSUE THREAD

**Issue by gruberb** [gruntjs/grunt-contrib-uglify#337]
Uglify fails wiht jquery.min.js and underscore-min.map. The errors are appearing just before the "3".

```
//# sourceMappingURL=underscore-min.map
{"version":3,"file":"underscore-min.js","sources".....
```

```
/# sourceMappingURL=jquery.min.map
{"version":3,"file":"jquery.min.js......
```
I combine all files in one (grunt-contrib-concat) and then use uglify to minimize the file. 
Does anyboday have the same issues?

**Comment by liselnicole** [comment]
I am seeing the same thing.

**Comment by benjaminsuch** [comment]
The error occures, when you include ".map" files in your concatenation. Grunt-Uglify can't handle them. Remove the ".map" files from your concat-task and it should work.

**Comment by julmot** [comment]
For me this occurred because I was using `const`. This message is useless to find the real problem...
