### ISSUE TITLE
Very Slow Performance on CentOS7 with iojs 1.0.3

### ISSUE THREAD

**Issue by nicksorrentino** [gruntjs/grunt-contrib-uglify#339]
I am using grunt and have the default uglify
 uglify: {},

On my macbook it takes about 31 seconds
On my Box with CentOS7 it takes > 20 minutes.

To test performance I turned on mangling and compression.  This still took 135 seconds.
uglify: {
      options: {
        mangle: false,
        compress: false,
        maxLineLen: 0
      }
    }

All the other grunt tasks seem to run at a reasonable speed.  It is uglifying two files.  One is 55k lines the other is 61k.

**Comment by sindresorhus** [comment]
That's an Uglify issue and nothing to do specifically with this plugin.
