### ISSUE TITLE
--mangle-regex

### ISSUE THREAD

**Issue by garygreen** [gruntjs/grunt-contrib-uglify#340]
Is it possible to supply this as an option? 

> You can also use a regular expression to define which property names should be mangled. For example, --mangle-regex="/^_/" will only mangle property names that start with an underscore.

**Comment by milkisevil** [comment]
Looks like [mishoo/UglifyJS2](https://github.com/mishoo/UglifyJS2) hasn't released this feature yet (as of v2.4.23). I had to `npm install mishoo/UglifyJS2` to get this. I guess it should only be added to grunt-contrib-uglify when properly released. 

But +1 for when that happens!

**Comment by bhamodi** [comment]
@milkisevil @garygreen - it has been properly released as of v2.4.24. Can we update to use the latest version?

**Comment by sindresorhus** [comment]
No. Go learn semver.

**Comment by garygreen** [comment]
@sindresorhus thanks for friendly advise :stuck_out_tongue_winking_eye:

**Comment by reppners** [comment]
So.. how can I use the mangle-regex option with grunt? Is it integrated yet?
