### ISSUE TITLE
Chrome and firefox debugger not working with sourcemap

### ISSUE THREAD

**Issue by ayeressian** [gruntjs/grunt-contrib-uglify#343]
When minified and sourcemap has been used. The debugger is not working as expect. For example You can't put breakpoints properly.

**Comment by lonelyelk** [comment]
I have the same problem. Source mapping url calculator insists on putting relative path to source map in special comment
```javascript
//# sourceMappingURL=script.js.map
```
But chrome browser needs it to be absolute path. If I correct it like this:
```javascript
//# sourceMappingURL=/js/script.js.map
```
mapping works fine. But I can't find any way to explicitly specify this way to locate the map.

**Comment by alexlamsl** [comment]
There has been fixes to source-map on `uglify-js@3`, so this may already be addressed.

Please report to https://github.com/mishoo/UglifyJS2/issues with reproducible test case if this is still an issue.
