### ISSUE TITLE
Doesn't work when compiling certain vendor libraries together

### ISSUE THREAD

**Issue by hguiney** [gruntjs/grunt-contrib-uglify#351]
Was trying to use this in an AngularJS project via [generator-ngbp](https://github.com/thardy/generator-ngbp), but the compiled JavaScript ultimately choked on the inclusion of  [stacktrace.js](https://github.com/stacktracejs/stacktrace.js) and [ui-router-extras](https://github.com/christopherthielen/ui-router-extras), both with the following error:

> Uncaught TypeError: angular.module(...).directive(...) is not a function

Those two libraries are not related; they are maintained by different people; one is vanilla JS and the other is an Angular plugin. So I'm wondering if this is an issue that has occurred, or would occur with other libraries. Not sure exactly what causes this as I'm on a work deadline and can't look too closely at it right now.

I previously [filed an issue](https://github.com/thardy/generator-ngbp/issues/30) with generator-ngbp but that was the wrong place for it. Is this the right place? Does it belong upstream with uglify proper? Or at stacktrace and ui-router-extras, respectively?

**Comment by XhmikosR** [comment]
This seems unrelated to grunt-contrib-uglify; try reporting the issue upstream.

**Comment by mikila85** [comment]
did you solve it eventually?

**Comment by hguiney** [comment]
@mikila85 Filed this last year so I don’t remember. But it looks like I had a deadline to meet so I just excluded the plugins that were causing problems rather than spending a bunch of time trying to get them to work. Sorry I can’t be of more help.

**Comment by mikila85** [comment]
Thx anyways :)
