### ISSUE TITLE
uglify task to execute only once , no more info

### ISSUE THREAD

**Issue by jiw0220** [gruntjs/grunt-contrib-uglify#355]
D:\workspace\html5\AnpiSportMobileWeb_release>grunt
Running "clean:0" (clean) task
>> 1 path cleaned.

Running "copy:copySysStyle" (copy) task
Copied 1 file

Running "copy:copyZepto" (copy) task
Copied 1 file

Running "copy:copyActivity" (copy) task
Copied 8 files

Running "copy:copyUser" (copy) task
Copied 4 files

Running "uglify:releaseA" (uglify) task

D:\workspace\html5\AnpiSportMobileWeb_release>

![image](https://cloud.githubusercontent.com/assets/6737088/10037358/c46432c4-61e7-11e5-9456-21b9b201040f.png)

		uglify : {
			options : {
				mangle : true
				preserveComments : false,
			},
		
			releaseA : {
				files : {
					'<%= DEST_PATH %>sys.js' : '<%=SOURCE_PATH%>sys.js'
				}
			},
			releaseB : {
				files : {
					'<%=DEST_PATH%>a/detail.js' : '<%=SOURCE_PATH%>a/detail.js',
					'<%= DEST_PATH %>a/list.js' : '<%= SOURCE_PATH %>a/list.js',
					'<%= DEST_PATH %>a/signs.js' : '<%= SOURCE_PATH %>a/signs.js',
					'<%= DEST_PATH %>a/suc.js' : '<%= SOURCE_PATH %>a/suc.js',
					'<%= DEST_PATH %>u/center.js' : '<%= SOURCE_PATH %>u/center.js',
					'<%= DEST_PATH %>u/regist.js' : '<%= SOURCE_PATH %>u/regist.js',
					'<%= DEST_PATH %>u/login.js' : '<%= SOURCE_PATH %>u/login.js'
				}
			},

**Comment by m0ngr31** [comment]
What does your `grunt.registerTask('default')` look like?

**Comment by sindresorhus** [comment]
Closing because of lack of response from OP.
