### ISSUE TITLE
install command causes all mods to download

### ISSUE THREAD

**Issue by erinlehmkuhl** [gruntjs/grunt-contrib-uglify#359]
I am fairly new to Grunt but I used this a month ago and it worked. This time when I ran the 'npm install grunt-contrib-uglify --save-dev' command it downloaded 4000+ files.  It could be user error on my part since I'm new to this but I write to you in case  this is the intended use and I missed a flag or something.

**Comment by vladikoff** [comment]
You should get something like this when you install:

```
➜  sl  npm install grunt-contrib-uglify --save-dev 
npm WARN package.json sl@1.0.0 No description
npm WARN package.json sl@1.0.0 No repository field.
npm WARN package.json sl@1.0.0 No README data
grunt-contrib-uglify@0.9.2 node_modules/grunt-contrib-uglify
├── uri-path@0.0.2
├── lodash@3.10.1
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── uglify-js@2.5.0 (uglify-to-browserify@1.0.2, async@0.2.10, source-map@0.5.1, yargs@3.5.4)
└── maxmin@1.1.0 (figures@1.4.0, gzip-size@1.0.0, pretty-bytes@1.0.4)
```

So it downloads several dependencies to run the task. let us know if you have other issues
