### ISSUE TITLE
Causes JS errors when minifying scrollMagic

### ISSUE THREAD

**Issue by Dan503** [gruntjs/grunt-contrib-uglify#362]
When I minify the scroll magic code (found on http://scrollmagic.io/) it produces this error:

`````````````````````
Uncaught ScrollMagic.Controller init failed.
`````````````````````

I get that error from a file that is just the scroll magic code + `var ctrl = new ScrollMagic.Controller();`

It's not really that big of an issue since we can load scrollMagic from a CDN source, bypassing the need to run grunt uglify on it. I just thought it might be helpful for finding a potential flaw in your minification algorithm.

**Comment by sindresorhus** [comment]
Should be posted on the Uglify issue tracker, not here.

**Comment by sgtpenguin** [comment]
Btw I found the error does not happen if you include the unminified version of ScrollMagic and uglify that along with your other libs

**Comment by bipashant** [comment]
Getting same error on Ruby On Rails application on the Production environment.
