### ISSUE TITLE
Please tag new version for uglify.js update

### ISSUE THREAD

**Issue by plynchnlm** [gruntjs/grunt-contrib-uglify#371]
uglify.js was recently updated to a version that avoids a [vulnerability](https://nodesecurity.io/advisories/48) but the latest tagged version does not include that change, so npm installs the version without that fix.

**Comment by avdg** [comment]
I believe this is fixed as there have been new releases by now, but I still have to do extra checks. In case you can conclude this faster, is this fixed so we can close this issue?

Thanks

**Comment by plynchnlm** [comment]
I tried the newest version, 0.11.0, and I got 2.6.1 of uglify-js, so I will close this.  Thanks!
