### ISSUE TITLE
ES6 string templates support

### ISSUE THREAD

**Issue by danielckv** [gruntjs/grunt-contrib-uglify#373]
I found that when I'm using template string in ES6 in my code it's just crashes grunt proccess: 

```
function parseActivity(action, type, title) {
      function aAn(str) {
          return ['a', 'e', 'i', 'o', 'u'].indexOf(str[0]) != -1 ? `an ${str}` : `a ${str}`
      };
     return `${action} ${aAn(type)}  :  ${title}`;
};
```

*Unexpected character '`'.*

**Comment by martingg88** [comment]
any update on this issue?

**Comment by avdg** [comment]
In short:

- This project relies on UglifyJS2 to do the heavy lifting, which is used as npm dependency
- UglifyJS2 (the upstream branch) has a harmony branch
- The harmony branch is not released on npm or is merged with the main branch (and released afterwards).

So, unless there will be a npm release on [mishoo/UglifyJS2](http://github.com/mishoo/UglifyJS2) or have an other way to include the code, it will be very unlikely to have es6 support just yet.
