### ISSUE TITLE
sourceMapRoot is ineffective

### ISSUE THREAD

**Issue by kathiedart** [gruntjs/grunt-contrib-uglify#376]
Hello

When using sourceMapRoot in the options it doesn't actually do anything, it doesn't tell me it's wrong and it doesn't change the source map root. Can you suggest why?

E.g.:
uglify: {
            external: {
                options: {
                    sourceMap: true,
                    sourceMapRoot: 'public/',
                },
                files: {
                    'public/js/external.js': [
                        'public/src/external/*_/_.js'  
                    ]
                }
            }
        }

Cheers

**Comment by alexlamsl** [comment]
With the latest version `sourceMap.root` should do what you expect. More documentation here:
https://github.com/mishoo/UglifyJS2#source-map-options

**Comment by eddiemonge** [comment]
Nope, still doesn't seem to do anything
