### ISSUE TITLE
Concatenating String & Variable With Dot Notation = Error?

### ISSUE THREAD

**Issue by johnjspiteri** [gruntjs/grunt-contrib-uglify#378]
I am Uglifying some Angular, and getting an error hitting a block where I am concatenating a string and a variable... for MongoDB I need to reference the array index using dot notation...

```javascript
    ['images.exterior.' + index]: content,
```
Error message is: 
<b><i>Warning: Uglification failed. Unexpected token: string (images.exterior.).</i></b>

Weird issue for me where I don't even know where to start looking? Can anyone recommend another way to concatenate that string and variable as a key?

Thank you
John

**Comment by avdg** [comment]
This must be the syntax used in json object notation no? UglifyJS2 doesn't support them except maybe on the harmony branch.

There is no such support yet in grunt-contrib-uglify unless the package.json uses the UglifyJS2's experimental harmony branch.

**Comment by johnjspiteri** [comment]
@avdg, you inspired me to look at this differently...
```javascript
var holder = {};
holder["images.interior."+ index] = content;
```
Wrapping up the concatenation made this pass through Uglify, and still work with Mongoose.
$set: holder

**Comment by avdg** [comment]
Yes, that should work fine :-)
