### ISSUE TITLE
unable to use 'exceptionsFiles' option

### ISSUE THREAD

**Issue by morious** [gruntjs/grunt-contrib-uglify#380]
when using the exceptionsFiles opion I am getting:
'Warning: Unexpected token'
and unable to perform a minification.

was anyone able to use this option?

**Comment by jrtitus** [comment]
@morious Can you post a few things?
1) Your declaration of the `mangleProperties` option
2) Your declaration of the `exceptionsFiles` option
3) The source from the JSON files specified in your `exceptionsFiles` option
(Is it possible you have an error in one of the JSON files? This can be checked with http://jshint.com/)
