### ISSUE TITLE
variable moved after function which is not desirable 

### ISSUE THREAD

**Issue by bhuvangu** [gruntjs/grunt-contrib-uglify#381]
Original code:

    var myApp = 1;
    function ApplicationRunner() {   
    }

minifed code:

    /*! test - v0.0.0 2015-12-28 */
    function ApplicationRunner(){}var myApp=1;

Notice `myApp=1` is moved after function in min code.

    uglify: {
    		options: {
    		  mangle: false,
    		  banner: '/*! <%= pkg.name %> - v<%= pkg.version %> <%= grunt.template.today("yyyy-mm-dd") %> */\n'
    		},
    		build: {
    		  src: 'built.js',
    		  dest: 'built.min.js',
    		}
   	}

using `v0.11.0`

**How to tell uglify not the move code ?**

**Comment by UltCombo** [comment]
In your example, there is absolutely no semantic difference. When entering an execution context, Function Declarations are always instantiated before any other statements are run.

Issues with the output should generally be reported in the [Uglify repository](https://github.com/mishoo/UglifyJS2), but as far as I see this is a non-issue.

**Comment by XhmikosR** [comment]
Closing because this is an upstream issue.

**Comment by UltCombo** [comment]
@XhmikosR An upstream *non-*issue, to be more precise. :stuck_out_tongue:
