### ISSUE TITLE
Sourcemaps - empty code window for sourcemapped file

### ISSUE THREAD

**Issue by QuintinS** [gruntjs/grunt-contrib-uglify#382]
Hi,

I'm unsure if this is an issue with contrib-uglify or with Chrome. I have reinstalled both Chrome, grunt, grunt-contrib-uglify to the latest version and the problem persists.

When clicking on an error line number in the console, I'm taken to the correct partial as mapped by grunt-contrib-uglify, but the code window is empty.

I can work around this for now by using beautify and disabling sourcemaps, but would appreciate some insights.

Thanks!
![capture](https://cloud.githubusercontent.com/assets/6787708/12296539/08b121e0-ba11-11e5-900f-251e8f4a7521.JPG)

**Comment by QuintinS** [comment]
Bump

**Comment by QuintinS** [comment]
I've discovered the reason for the issue by looking at the debugger in Firefox Dev. The sourcemap is pointing to a source which is not in localhost on my machine.

My file structure looks like this:

`
/
/wwwroot // <-- Localhost
/_dev <-- Location of source files
/_project <-- location of gruntfile.js
`
All dev files are inside the /dev/ folder, which is being correctly pointed to... but as the folder is not on the localhost, it was resolving to a 404, which in Chrome Debugger appears as a blank screen. Firefox Dev generated the HTML for a 404 inside the debugger which gave me a clue as to what the problem was.

My gruntfile looks like so:

`
		uglify: {

			common: {
				options: {
					mangle: false,
					compress: true, // true or false or {}
					preserveComments: 'all', // true or 'all' or 'some'
					sourceMap : true'
				},
				files: {
					// '../wwwroot/Content/includes/js/libs.js': ['../_dev/js/common/libs/*.js'],
					'../wwwroot/Content/includes/js/buildbar.js': ['../_dev/js/common/buildbar/*.js'],
					'../wwwroot/Content/includes/js/framework.js': ['../_dev/js/common/framework/*.js'],
				}
			},

		}
`
I understand there might be a way to use sourceMapRoot to point the browser to a different location, but as the location will be outside of localhost I'm not sure how to proceed.

Bizarrely it was working fine until a month or so ago. I may have updated to a later version of the package without realising.

Is there a way that I can resolve this without needing to change my directory structure?

**Comment by mcpengelly** [comment]
I also experience this. Is there any solution? Am I missing something?

**Comment by antonpantev** [comment]
I don't think this is a bug with grunt-contrib-uglify. 

Try using `sourceMapIncludeSources: true` in your uglify options.

This will include the original source file inside of your map files instead of trying to reach the files located outside of your localhost.

**Comment by distinctdan** [comment]
I had a similar issue and it turned out to be my sourceMapRoot was set incorrectly. If you look at your generated sourcemap file, you can see what the root is and also what the file paths are. In my case, the file paths were missing one folder, so I added it to the sourceMapRoot property.

**Comment by alexlamsl** [comment]
There have been fixes to source-map on `uglify-js@3`, so this may already be addressed.

Please report to https://github.com/mishoo/UglifyJS2/issues with reproducible test case if this is still an issue.
