### ISSUE TITLE
task suspended,after running "uglify" task

### ISSUE THREAD

**Issue by jiw0220** [gruntjs/grunt-contrib-uglify#385]
![image](https://cloud.githubusercontent.com/assets/6737088/12416641/8cb08258-bedd-11e5-98f7-5116787eff0c.png)
As shown.This task "test" was suspended

----------------

![image](https://cloud.githubusercontent.com/assets/6737088/12416747/32452fde-bede-11e5-8f70-df6efcadc62f.png)

chang "uglify" index,wrong again

pls,help me.....

my task config
![image](https://cloud.githubusercontent.com/assets/6737088/12416829/ab35892a-bede-11e5-96e8-94313cfb1afe.png)

**Comment by avdg** [comment]
Please reopen if this is a bug on grunt-contrib-uglify. For help you might be better of on [stackoverflow](https://stackoverflow.com/questions/tagged/grunt-contrib-uglify) though
