### ISSUE TITLE
Object #<Object> has no method 'gzipSync'

### ISSUE THREAD

**Issue by llaumgui** [gruntjs/grunt-contrib-uglify#391]
Hi,

since the 0.11.1 release, I have this message:
~~~
Running "uglify:moment" (uglify) task
Warning: Object #<Object> has no method 'gzipSync' Use --force to continue.

Aborted due to warnings.
~~~

If I use report=min instead of gzip, I have no problem.
If I use 0.11.0 instead of 0.11.1, I haven't any problem.

I think that a dependency missing in 0.11.1.

Thx.

**Comment by bricss** [comment]
+1, got same problem after version update :3

**Comment by ArthurAssuncao** [comment]
Using node 0.10.x?
In install (npm install) get this message?
npm WARN engine gzip-size@3.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"v0.10.25","npm":"1.3.10"})

**Comment by XhmikosR** [comment]
I don't see those warnings on our CI builds which run on 0.10.

**Comment by XhmikosR** [comment]
Closing since everything looks good here.

If you still have the issue, report back with more info, node version, npm version etc,.
