### ISSUE TITLE
"preserveComments" destroys RequireJS library

### ISSUE THREAD

**Issue by jens-duttke** [gruntjs/grunt-contrib-uglify#392]
**First problem:**
Since version 0.10.0 the option "preserveComments": "some" doesn't work anymore.
It returns the same result as "preserveComments": "all".
Till version 0.9.2 that worked fine.
I tried version 0.11.1, 0.11.0, 0.10.1 and 0.10.0 and they all have the same problem.

The workaround (`/(?:^!|@(?:license|preserve|cc_on))/`) which has been posted in issue #366 works for me, but your documentation still show 'some' as valid option.

**Second problem:**
If I try to uglify the RequireJS library, the faulty "preserveComments": "some" option (but also the setting "all") will destroy the library.
Which means, the uglified file does not work anymore.

The problem is, that it uglifies line 1995 to 2033 of the uncompressed RequireJS 2.1.22 (https://github.com/jrburke/r.js/blob/master/require.js) into this:
```
eachReverse(scripts(),function(a){return
//Set the 'head' where we can append children by
//using the script's parent.
head||(head=a.parentNode),dataMain=a.getAttribute("data-main") ...
```

Like you see, it puts a comment between the return statement and the return value.
Because of JavaScript's automatic semicolon insertion I get an "unreachable code after return statement" error in Firefox and the library doesn't work anymore.

My configuration looks like this:
```
uglify: {
	options: {
		screwIE8: true
	},
	libs: {
		options: {
			preserveComments: 'some'
		},
		files: [
			{
				expand: true,
				cwd: '<%= pkg.distribution %>/static/<%= pkg.version %>/js',
				src: ['lib/*.js'],
				dest: '<%= pkg.distribution %>/static/<%= pkg.version %>/js'
			}
		]
	}
},
```

**Comment by claudiosmweb** [comment]
I have the same problem.

**Comment by XhmikosR** [comment]
1st problem: you are welcome to make a PR to update the docs.
2nd problem: unrelated to grunt-contrib-uglify; try reporting the issue upstream.
