### ISSUE TITLE
feature request: override uglifyjs version for harmony

### ISSUE THREAD

**Issue by tswaters** [gruntjs/grunt-contrib-uglify#393]
It would be quite useful to provide an override for the uglify engine, similar to how [grunt-mocha-istanbul allows for overriding the coverage tool it uses](https://github.com/pocesar/grunt-mocha-istanbul#compatible-tools).

This would be specifically so that one could install the harmony branch locally in one's project and provide that version to grunt-contrib-uglify via options, e.g.:

```
uglify: {
  options: {
    engine: require('uglify-js')
  }
}
```

In tasks/lib/uglify.js - instead of requiring at the top, take the engine from options and, if not provided, fall back on the one included with grunt-contrib-uglify.

Thoughts?

**Comment by avdg** [comment]
I might prefer to go dual stack. I had some conversation on here https://github.com/SoftwearDevelopment/grunt-contrib-uglify/commit/e026537146a77065bc70090692918f311cdeabe0

This sees doable, we'll just throw in a harmony option I guess

**Comment by avdg** [comment]
It seems that dependencies are installed named as in package.json. Not sure how to avoid the naming conflict.

**Comment by XhmikosR** [comment]
https://github.com/gruntjs/grunt-contrib-uglify/tree/harmony
