### ISSUE TITLE
Add support for UglifyJS `--screw-ie8` option

### ISSUE THREAD

**Issue by mgol** [gruntjs/grunt-contrib-uglify#40]
See https://github.com/mishoo/UglifyJS2/commit/26746ce3167a768479435588dd9099bb7408018f and https://github.com/mishoo/UglifyJS2/commit/75f0bbe6e8a243571860626631a820b0787b9990 for changesets introducing the option to UglifyJS 2.

Basically, `--screw-ie8` disables hacks used to retain compatibility with IE<9. The drawback is, it also introduces bugs, see e.g.: https://github.com/mishoo/UglifyJS/issues/485

In some environments where support for IE<9 is not needed (I'm working on two such projects right now) passing `--screw-ie8` to `uglifyjs` is safer than not doing that.

**Comment by wslx520** [comment]
for others who come here, the `screw_ie8` has been abandoned, the new option is : `ie8: true` , `uglify({ie8:true})`
