### ISSUE TITLE
Warning: Uglification failed.

### ISSUE THREAD

**Issue by Jonas-WMDE** [gruntjs/grunt-contrib-uglify#400]
I am getting this error when using usemin together with uglify (no options given):
Warning: Uglification failed.
Unexpected token: operator (*). 

As far as I can understand it happens when processing [underscore-min.js](http://underscorejs.org/)

**Comment by vladikoff** [comment]
Don't uglify minified code.

**Comment by vladikoff** [comment]
https://github.com/gruntjs/grunt-contrib-uglify/issues/233#issuecomment-49798903

**Comment by tamirgilany** [comment]
> Don't uglify minified code.

Thanks!
