### ISSUE TITLE
Unexpected token: operator (>).

### ISSUE THREAD

**Issue by sashberd** [gruntjs/grunt-contrib-uglify#401]
Hey guys,

I used in my code next ECMA6 JS code:
var indexToInsertFromLeft = galleryIndiciesData.findIndex(x => x === image.arrayIndex - 1);

And got next error:

  stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (C:\\Users\\Admi
nistrator\\Desktop\\ADDON-BUILD\\node_modules\\grunt-contrib-uglify\\node_module
s\\uglify-js\\tools\\node.js:22:1), <anonymous>:1526:18)\n    at js_error (eval
at <anonymous> (C:\\Users\\Administrator\\Desktop\\ADDON-BUILD\\node_modules\\gr
unt-contrib-uglify\\node_modules\\uglify-js\\tools\\node.js:22:1), <anonymous>:1
534:11)\n    at croak (eval at <anonymous> (C:\\Users\\Administrator\\Desktop\\A
DDON-BUILD\\node_modules\\grunt-contrib-uglify\\node_modules\\uglify-js\\tools\\
node.js:22:1), <anonymous>:2026:9)\n    at token_error (eval at <anonymous> (C:\
\Users\\Administrator\\Desktop\\ADDON-BUILD\\node_modules\\grunt-contrib-uglify\
\node_modules\\uglify-js\\tools\\node.js:22:1), <anonymous>:2034:9)\n    at unex
pected (eval at <anonymous> (C:\\Users\\Administrator\\Desktop\\ADDON-BUILD\\nod
e_modules\\grunt-contrib-uglify\\node_modules\\uglify-js\\tools\\node.js:22:1),
<anonymous>:2040:9)\n    at expr_atom (eval at <anonymous> (C:\\Users\\Administr
ator\\Desktop\\ADDON-BUILD\\node_modules\\grunt-contrib-uglify\\node_modules\\ug
lify-js\\tools\\node.js:22:1), <anonymous>:2554:9)\n    at maybe_unary (eval at
<anonymous> (C:\\Users\\Administrator\\Desktop\\ADDON-BUILD\\node_modules\\grunt
-contrib-uglify\\node_modules\\uglify-js\\tools\\node.js:22:1), <anonymous>:2716
:19)\n    at expr_ops (eval at <anonymous> (C:\\Users\\Administrator\\Desktop\\A
DDON-BUILD\\node_modules\\grunt-contrib-uglify\\node_modules\\uglify-js\\tools\\
node.js:22:1), <anonymous>:2751:24)\n    at maybe_conditional (eval at <anonymou
s> (C:\\Users\\Administrator\\Desktop\\ADDON-BUILD\\node_modules\\grunt-contrib-
uglify\\node_modules\\uglify-js\\tools\\node.js:22:1), <anonymous>:2756:20)\n
 at maybe_assign (eval at <anonymous> (C:\\Users\\Administrator\\Desktop\\ADDON-
BUILD\\node_modules\\grunt-contrib-uglify\\node_modules\\uglify-js\\tools\\node.
js:22:1), <anonymous>:2780:20)' }

Is you plugin supports such syntax?

**Comment by avdg** [comment]
UglifyJS doesn't support es6 with the exception of the experimental harmony branch. Grunt-contrib-uglify doesn't use the harmony branch to my knowledge.

Please track #393

**Comment by geooogle** [comment]
https://davidburgos.blog/how-to-fix-grunt-contrib-uglify-for-es6/
