### ISSUE TITLE
Please upgrade to the latest version of uglify. Several options do not work as expected.

### ISSUE THREAD

**Issue by vivekkodira1** [gruntjs/grunt-contrib-uglify#402]
Several options do not work as they should (ex: drop_debugger, unsafe). When I run the grunt task, several lines of code are being removed. These include 'debugger' statements. Here is an example below. 

### Source:
`var x = function() {
	debugger;
	console.log( "Hi" );
}`

### Options:
`"options":{
            /*sourceMap: false,*/
            /*beautify: true,*/
             mangle:false,
            sequences: false,  // join consecutive statemets with the “comma operator”
            properties: false,  // optimize property access: a["foo"] → a.foo
            dead_code: false,  // discard unreachable code
            drop_debugger: false,  // discard “debugger” statements
            unsafe: false, // some unsafe optimizations (see below)
            conditionals: false,  // optimize if-s and conditional expressions
            comparisons: false,  // optimize comparisons
            evaluate: false,  // evaluate constant expressions
            booleans: false,  // optimize boolean expressions
            loops: false,  // optimize loops
            unused: false,  // drop unused variables/functions
            hoist_funs: false,  // hoist function declarations
            hoist_vars: false, // hoist variable declarations
            if_return: false,  // optimize if-s followed by return/continue
            join_vars: false,  // join var declarations
            cascade: false,  // try to cascade `right` into `left` in sequences
            side_effects: false,  // drop side-effect-free statements
            warnings: false, // warn about potentially dangerous optimizations/code,
            keep_fnames: false
        },`

### Output
`var x=function(){console.log("Hi")};`

The same code pasted in [the online tool](http://lisperator.net/uglifyjs/#demo) works as expected so the issue looks to have been fixed in newer versions of uglify already. Please update the grunt task to use these versions.

**Comment by avdg** [comment]
grunt-contrib-uglify v1.0.1: https://github.com/gruntjs/grunt-contrib-uglify/blob/fe967c8e2235a0efd1d682459ce33940b92a0e6a/package.json#L22

I don't see anything wrong here

**Comment by vivekkodira1** [comment]
Hi Anthony, 
     The title is probably wrong. I didn't know which version of uglify was being used by the grunt task. And assumed that it may not be the latest because of the difference in behavior between the grunt task and the online tool. The observation is correct though: the grunt task is ignoring most of the options passed to it and is removing valid code while the online tool does not.

**Comment by avdg** [comment]
The options are categorised per phase (compress, output, etc...), did you read the readme?

**Comment by vivekkodira1** [comment]
Thanks Anthony. I didn't read the readme properly and was passing options by themselves without categorizing them.
