### ISSUE TITLE
 => operator not recognised

### ISSUE THREAD

**Issue by endymion1818** [gruntjs/grunt-contrib-uglify#407]
Got this JS_Parse_Error when demoing Bootstrap 4 alpha:

`Unexpected token: operator (>)`

The offending line of code is 

`const Util = (($) => {`

from [v4-alpha on Bootstrap](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/util.js)

I wish I knew more about more recent versions of JavaScript to be able to contribute more to this issue.

**Comment by avdg** [comment]
UglifyJS doesn't support it yet, there are some harmony implementations underway on the harmony branch though. See mishoo/UglifyJS2#448.

You could try harmony out yourself by replacing the version number to the git url `https://github.com/mishoo/UglifyJS2.git#harmony`
https://github.com/gruntjs/grunt-contrib-uglify/blob/f680e895de04be9ce90a23ebd8da49e571a823d8/package.json#L22

**Comment by endymion1818** [comment]
Thanks for the response, yes will give that a go.

**Comment by XhmikosR** [comment]
Closing since it's an upstream issue.
