### ISSUE TITLE
Documentation confusion: What are versions 2.x and 3.x?

### ISSUE THREAD

**Issue by MadaraUchiha** [gruntjs/grunt-contrib-uglify#408]
Hey guys, I'm having a bit of a trouble understanding the docs and the breaking changes.

The latest version for grunt-contrib-uglify is 1.x, for Grunt, 1.x, for Uglify, 2.x.

Could you clarify what you mean in the docs when you're explaining the migration path from 2.x to 3.x?

**Comment by ivnmaksimovic** [comment]
> Migrating from 2.x to 3.x

Shouldn't that be:

> Migrating from 1.x to 2.x

**Comment by XhmikosR** [comment]
I doubt it since 2.x was released a lot after that comment.

**Comment by XhmikosR** [comment]
Removed this in https://github.com/gruntjs/grunt-contrib-uglify/commit/3a718cfbb89abf70289e687d1e624c936259c3cd
