### ISSUE TITLE
Please freeze uglifyjs version

### ISSUE THREAD

**Issue by evanhuang8** [gruntjs/grunt-contrib-uglify#415]
Basically in the new uglifyjs version (2.7.0) they decided to flip the switch and enable `screw_ie8` by default, which this package's option does not override, and hence caused very unexpected behaviors. See this issue:

https://github.com/mishoo/UglifyJS2/issues/1201

Instead of `^2.4.24` maybe it's good to lock to the subversion as well, like `2.6.x`.

**Comment by avdg** [comment]
I'm not aware on the full impact of this change yet, but on long term ie8 support will be deprecated and removed anyway. Instead, I can only encourage to manually set the screw_ie8 flag manually for now and expect a full removal of the ie8 flag around the time when full harmony support will be introduced.

**Comment by evanhuang8** [comment]
It's true that IE8 support will be deprecated, but it should be marked on the documentation. As of now, setting the screwIE8 to false according to this grunt task's docs will not set the appropriate flags in uglifyjs. Since it's not a major version bumped (no version bumped at all in this project), it might catch users out of surprise when builds start to fail.

**Comment by avdg** [comment]
TODO
- [ ] Inform users about manually setting screwIE8 flag
- [ ] Inform users about screwIE8 changes from uglify

**Comment by XhmikosR** [comment]
We currently have `~2.6.2` meaning you won't get 2.7.0. For the next version we should bump the minor or major version.

https://github.com/gruntjs/grunt-contrib-uglify/compare/update-uglify

/CC @vladikoff

**Comment by mgibeau** [comment]
Using node 0.10.29 and npm 1.4.14 I got 2.7.0.

```
grunt-contrib-uglify@0.9.1 node_modules/grunt-contrib-uglify
├── uri-path@0.0.2
├── chalk@1.1.3 (escape-string-regexp@1.0.5, supports-color@2.0.0, ansi-styles@2.2.1, strip-ansi@3.0.1, has-ansi@2.0.0)
├── maxmin@1.1.0 (figures@1.7.0, pretty-bytes@1.0.4, gzip-size@1.0.0)
├── uglify-js@2.7.0 (uglify-to-browserify@1.0.2, async@0.2.10, yargs@3.10.0, source-map@0.5.6)
└── lodash@3.10.1
```

Also, you might want to add support for the `--support-ie8` option as described here: https://github.com/mishoo/UglifyJS2/commit/02c638209ee22816b1324ff0c0f47b27db1336af. In my case, turning off the `screwIE8` did not work, I had to manually downgrade the uglify-js lib to 2.6.x.

**Comment by XhmikosR** [comment]
@mgibeau: you are using an old version of the plugin.

```
C:\Users\xmr\Desktop\grunt\grunt-contrib-uglify>npm ls uglify-js
grunt-contrib-uglify@1.0.1 C:\Users\xmr\Desktop\grunt\grunt-contrib-uglify
├─┬ grunt-contrib-nodeunit@1.0.0
│ └─┬ nodeunit@0.9.1
│   └─┬ tap@0.7.1
│     └─┬ runforcover@0.0.2
│       └─┬ bunker@0.1.2
│         └─┬ burrito@0.2.12
│           └── uglify-js@1.1.1
└── uglify-js@2.6.4
```
