### ISSUE TITLE
uglifyjs error

### ISSUE THREAD

**Issue by Simple2012hcz** [gruntjs/grunt-contrib-uglify#420]
we use grunt-contrib-uglifyjs angularjs with default or mangle = false ,in android 2.3 os run error.
but uglifyjs2 uglify ,with option -m -o ,can run ok in android 2.3 .

**Comment by avdg** [comment]
Any idea how the error looks like? We like to be pinpointed to the cause of the error. Thanks

**Comment by XhmikosR** [comment]
Lack of info and probably an upstream issue, so closing.
