### ISSUE TITLE
Uglify with arrow function

### ISSUE THREAD

**Issue by vanduc1102** [gruntjs/grunt-contrib-uglify#421]
When my code has an arrow function like this:

return AAA.find((obj) => obj.vv == cant)[(cc ? "cc" : "ccc-sss")];

I got error

` message: 'SyntaxError: Unexpected token: operator (>)',`

**Comment by avdg** [comment]
Support for arrow functions are only available on the harmony branch of uglify-js. Although even that might not fully support correctly.

This can be enabled by having a clone of grunt-contrib-uglify and set the uglify version in package.json to `https://github.com/mishoo/UglifyJS2.git#harmony`.

Otherwise, feel free to follow the harmony status at mishoo/UglifyJS2#448

**Comment by XhmikosR** [comment]
Upstream issue.

**Comment by rainabba** [comment]
Still an upstream issue? Hard to imagine anything not supporting arrow functions these days.

**Comment by XhmikosR** [comment]
Of course an upstream issue. They have a branch for ES6 and I have made a
branch in the plugin for people who want to try that.

**Comment by rainabba** [comment]
I see the harmony branch now. Thank you. 

For anyone else looking for ES6 support, install harmony branch with `npm install git://github.com/gruntjs/grunt-contrib-uglify#harmony --save-dev`

**Comment by avdg** [comment]
@rainabba this repo has a harmony branch? I thought that UglifyJS (with `mishoo/UglifyJS2`) had that and this one doesn't.

Did you tried your suggestion out yourself?

**Comment by XhmikosR** [comment]
https://github.com/gruntjs/grunt-contrib-uglify/tree/harmony

**Comment by rainabba** [comment]
@avdg I did. In fact, I copied from my console to be sure there were no typos. You can see the branch at: https://github.com/gruntjs/grunt-contrib-uglify/tree/harmony

**Comment by avdg** [comment]
Nevermind, I checked the list, but apparently I missed the highlighted one (which was the harmony one) :/ wow

**Comment by amineparis** [comment]
You can use` function(x) { //do something } `

**Comment by XhmikosR** [comment]
`npm i grunt-contrib-uglify-es`
