### ISSUE TITLE
JSON shorthand can't assign to variable

### ISSUE THREAD

**Issue by ivianiac** [gruntjs/grunt-contrib-uglify#425]
The following JavaScript throws this error: Unexpected token punc «}», expected punc «:»
```
var options = {foo:"bar"}
var event = {options}
```

Working example: https://jsfiddle.net/IVIaniac/kj3a471x/

**Comment by UltCombo** [comment]
This plugin does not support ES2015 (ES6) yet, see https://github.com/gruntjs/grunt-contrib-uglify/issues/421#issuecomment-232933640

**Comment by avdg** [comment]
There is no harmony support yet in current shipped grunt-contrib-uglify plugin. Closing.

**Comment by ivianiac** [comment]
Please look closer this is not a Harmony / ES6 feature.

**Comment by UltCombo** [comment]
Yes, it is. https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Object_initializer#New_notations_in_ECMAScript_2015

**Comment by ivianiac** [comment]
Sorry for the misunderstanding. Thank you for the clarification.
