### ISSUE TITLE
Renaming Files Stops with First Period

### ISSUE THREAD

**Issue by Kelderic** [gruntjs/grunt-contrib-uglify#427]
**Steps to reproduce:**

Create a file named `stats-2.3.0.js`.

Run grunt-contrib-uglify using:

```js
uglify: {
    my_target: {
        files: [{
            expand: true,
            cwd: 'path/to/files',
            src: ['**/*.js','!**/*.min.js'],
            dest: 'path/to/files',
            ext: '.min.js'
        }]
    }
}
```

**Expected behavior:**

File should be renamed to `stats-2.3.0.min.js`.

**Actual behavior:**

File is renamed to `stats-2.min.js`.

**Comment by XhmikosR** [comment]
Confirmed.

/CC @shama @vladikoff

**Comment by XhmikosR** [comment]
Hmm, actually this is probably by design.

Try `extDot: 'last'` http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically

**Comment by Kelderic** [comment]
Oops, yep that is the issue right there. Thanks @XhmikosR. Closing the ticket.
