### ISSUE TITLE
preserveComments does not enable all options of UglifyJS comments

### ISSUE THREAD

**Issue by cheshrkat** [gruntjs/grunt-contrib-uglify#430]
There is a lot of cross-purposes discussion on other threads about `preserveComments:some` that never matched the upstream UglifyJS repo. This issue is not directly concerned with that option, although the fix is to map its behaviour to the correct configuration.

[As per other threads](https://github.com/gruntjs/grunt-contrib-uglify/issues/426#issuecomment-239844320), grunt-contrib-uglify is supposed to be passing through to the UglifyJS API, but the bug is that the option _does not map correctly_ to UglifyJS.

[From UglifyJS](https://github.com/mishoo/UglifyJS2) [as linked from contrib uglify](https://github.com/gruntjs/grunt-contrib-uglify):

> --comments                    Preserve copyright comments in the output. By
>                                 default this works like Google Closure, keeping
>                                 JSDoc-style comments that contain "@license" or
>                                 "@preserve". You can optionally pass one of the
>                                 following arguments to this flag:
>                                 - "all" to keep all comments
>                                 - a valid JS regexp (needs to start with a
>                                 slash) to keep only comments that match.

Note "Preserve _copyright_ comments in the output." is the default. 
# Expected mappings

By my reading of the UglifyJS API, grunt-contrib-uglify should be mapping as follows...
- `true` equivalent to `--comments`, where preservation syntax is honoured but other comments are stripped
- `false` equivalent to omitting  `--comments`, where all comments are stripped
- `all` equivalent to `--comments all`, where all comments are preserved regardless of syntax
- a regex function
# Actual result

grunt-contrib-uglify incorrectly maps `true` to `--comments all` and keeps all comments, when _it should only keep comments with preservation syntax_ as per the Uglify docs quoted above.

grunt-contrib-uglify has no working equivalent of `--comments`, that is retaining license comments but stipping other comments (which is what `some` used to do).
# Suggested fix

The fix should be to match the API as per "CORRECT MAPPINGS", which is what this plugin is reportedly trying to do. The requested fix is _not_ to reinstate `some`, which is where the other threads got confused.

I've had a quick look at the code and I'm not clear why the current code doesn't produce the correct result. To put it another way, I can't give you a PR to fix this. Hopefully someone more familiar with this project will know what to do.

To help as best I can, what follows are details of the tests I've done and the files used; hopefully this will help someone else pick this up.
# Test results

I've tested this on both OSX and Windows 10 (using the ubuntu subsystem) with the same results. First I've tested UglifyJS on the CLI to get a baseline result; then I've tested trying to reproduce those results with grunt-contrib-uglify.

Test 1, ulglifyjs (no args):

```
$ uglifyjs test.js
```

Test 1 output:

```
var hai=document.createElement("p");hai.innerText="JavaScript has loaded.";document.getElementsByTagName("body")[0].appendChild(hai);
```

Test 2, ulglifyjs  (comments):

```
$ uglifyjs test.js --comments
```

Test 2 output (note only the explicitly preserved comments are preserved)

```
/* @preserve preserved comment */
/* @preserve preserved comment
 *
 */
/* @license preserved comment
 *
 */
/* @cc_on preserved comment */
var hai=document.createElement("p");hai.innerText="JavaScript has loaded.";document.getElementsByTagName("body")[0].appendChild(hai);
```

Test 3, ulglifyjs  (comments all):

```
$ uglifyjs test.js --comments all
```

Test 3 output:

```
/*! Preserved comment */
/* @preserve preserved comment */
/* @preserve preserved comment
 *
 */
/* @license preserved comment
 *
 */
/* @cc_on preserved comment */
/* Unpreserved comment */
// Unpreserved comment
var hai=document.createElement("p");hai.innerText="JavaScript has loaded.";document.getElementsByTagName("body")[0].appendChild(hai);
```

Test 4, grunt-contrib-uglify set to `preserveComments: true`

Output:

```
/*! Preserved comment */
/* @preserve preserved comment */
/* @preserve preserved comment
 * 
 */
/* @license preserved comment
 * 
 */
/* @cc_on preserved comment */
/* Unpreserved comment */
// Unpreserved comment
var hai=document.createElement("p");hai.innerText="JavaScript has loaded.",document.getElementsByTagName("body")[0].appendChild(hai);
```

_This is the bug_: This should match the behaviour of `--comments`, where preservation syntax is honoured but other comments are stripped; but grunt-contrib-uglify actually matches the behaviour of `--comments all` where it keeps all comments.

Test 5, grunt-contrib-uglify set to `preserveComments:false`

Output:

```
var hai=document.createElement("p");hai.innerText="JavaScript has loaded.",document.getElementsByTagName("body")[0].appendChild(hai);
```

Correctly matches behaviour of omitting the comments flag in Uglify.

Test 6, grunt-contrib-uglify without any value set for `preserveComments`

Test 6 Output:

```
var hai=document.createElement("p");hai.innerText="JavaScript has loaded.",document.getElementsByTagName("body")[0].appendChild(hai);
```

Correctly matches omission of the argument in Uglify.

Test 7, grunt-contrib-uglify set to `preserveComments: 'all'`

Test 7 Output: 

```
/*! Preserved comment */
/* @preserve preserved comment */
/* @preserve preserved comment
 * 
 */
/* @license preserved comment
 * 
 */
/* @cc_on preserved comment */
/* Unpreserved comment */
// Unpreserved comment
var hai=document.createElement("p");hai.innerText="JavaScript has loaded.",document.getElementsByTagName("body")[0].appendChild(hai);
```

Correctly matches `--comments all` in Uglify.
# Files to reproduce test results

gruntfile

```
module.exports = function (grunt) {

  grunt.loadNpmTasks('grunt-contrib-uglify');

  // Project configuration.
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),

    uglify: {
      options: {
        preserveComments: true
      },
      build: {
        src: 'test.js',
        dest: 'test-all.min.js'
      }
    }

  });

  grunt.registerTask('default', ['uglify']);

}
```

package.json

```
{
  "name": "grunt-contrib-uglify-test",
  "version": "0.1.0",
  "description": "Test cases",
  "main": "gruntfile.js",
  "devDependencies": {
    "grunt": "1.0.x",
    "grunt-contrib-uglify": "2.0.x"
  }
}
```

test.js

```
/*! Preserved comment */

/* @preserve preserved comment */

/* @preserve preserved comment
 * 
 */

/* @license preserved comment
 * 
 */

/* @cc_on preserved comment */

/* Unpreserved comment */

// Unpreserved comment

var hai=document.createElement("p");
hai.innerText="JavaScript has loaded.";
document.getElementsByTagName("body")[0].appendChild(hai);
```

**Comment by avdg** [comment]
Please do note that a major part of this issue may be caused due to having 2 different api's on the side of UglifyJS. The CLI api doesn't fully match the internal library api.

**Comment by cheshrkat** [comment]
Ahh that explains a lot - didn't realise Uglify had divergent APIs (how annoying!). 

> The code generator can keep certain comments in the output. If you pass comments: true it'll keep all comments. You can pass a RegExp to retain only comments whose body matches that regexp. You can pass a function for custom filtering. For example, when --comments is passed with no argument the command-line tool will keep all comments containing "@license", "@preserve" or "@cc_on".

I guess this is why `some` happened in the first place. It was probably the right solution given the constraints :-/

**Comment by avdg** [comment]
Created mishoo/UglifyJS2#1285

**Comment by avdg** [comment]
If there are confusions about the passthrough function parameter usage, the first parameter is the containing node where the comment is nested in, the second is the comment token (of which property `value` contains the comment).

Due to api being this way I am not able to make changes to the parameters. Documentation fixes may be suggested in the above pr though.

**Comment by XhmikosR** [comment]
This should be sorted with #472, right @alexlamsl?

**Comment by alexlamsl** [comment]
Yup - after #472 this will now be just `output.comments`, and https://github.com/mishoo/UglifyJS2#keeping-copyright-notices-or-other-comments should detail its possible forms.

**Comment by adumesny** [comment]
@alexlamsl how does one specify `output.comments` in the json ? I tried child/syblind of `options` and different formats and can't get it to work nor find example (grunt-contrib-uglify@4.0.1 and uglify-js@3.6.7).
