### ISSUE TITLE
Generated source maps and debugging problem

### ISSUE THREAD

**Issue by ndjordjevic** [gruntjs/grunt-contrib-uglify#436]
Hi,

Generated source maps with the latest grunt-contrib-uglify looks fine, but in chrome dev tools you can't put a brakepoint on some lines where it can be put in original source and even stepping looks strange. It looks like that something is wrong with generated source maps itself. Anyone experienced the similar problem?
In Firefox you can put a breakpoint on every line in source map, but again stepping is strange and jumps to places where it's should not.

**Comment by alexlamsl** [comment]
There has been fixes to source-map on `uglify-js@3`, so this may already be addressed.

Please report to https://github.com/mishoo/UglifyJS2/issues with reproducible test case if this is still an issue.

**Comment by dinbtechit** [comment]
This is still an issue.

```
  "devDependencies": {
    "grunt": "^1.3.0",
    "grunt-cli": "1.3.2",
    "grunt-contrib-clean": "2.0.0",
    "grunt-contrib-uglify": "5.0.0",
    "grunt-contrib-less": "3.0.0",
    "grunt-contrib-watch": "1.1.0",
    "grunt-bless": "1.0.2"
  }
```
