### ISSUE TITLE
Issue referencing non existing file in banner: grunt.file.read('...'),

### ISSUE THREAD

**Issue by chrisj-skinner** [gruntjs/grunt-contrib-uglify#437]
Below is a link to explain the issue in more detail but in short I'm getting an Error: ENOENT when trying to reference a file created in a concat task using uglify banner.

This fails if the file does not exist
`banner: grunt.file.read('concat/destinationFile/file.js'),`

Would be great to do something like
`banner: grunt.file.read(grunt.concat.dev.files.dest),`

Or
`banner: grunt.concat.dev.files.dest`

[error-enoent-in-grunt-uglify-task](http://stackoverflow.com/questions/39878786/error-enoent-in-grunt-uglify-task)

**Comment by XhmikosR** [comment]
You should be able to do what you want already; just make sure you reference the file the right way.

```js
banner: '<%= grunt.concat.dev.files.dest %>'
```
