### ISSUE TITLE
Add branch #harmony

### ISSUE THREAD

**Issue by franciscop** [gruntjs/grunt-contrib-uglify#440]
I tried to make a PR but apparently you cannot create a new branch for a PR. I suggest adding a new branch called `harmony` to grunt-contrib-uglify that includes this in the package.json:

```json
"uglify-js": "https://github.com/mishoo/UglifyJS2.git#harmony",
```

So we can include in our package.json just `"grunt-contrib-uglify": "https://github.com/gruntjs/grunt-contrib-uglify.git#harmony"` instead of having to clone and maintain it locally.

**Comment by avdg** [comment]
Not sure how npm will handle this as it will only maintain 1 reference for each package name while we have to handle 2 packages with the same name. This would require some npm voodoo powers to resolve the issue.

**Comment by franciscop** [comment]
Ah I see how this could be a problem, no problem then, I close the issue

**Comment by avdg** [comment]
There are duplicated issues anyway like #393. But sadly still no solution/workaround (unless local checkout and change uglify ref to github repo) except waiting till uglify harmony has been completed.
