### ISSUE TITLE
Wrong urgly: (function(){return function(a){console.log(a);}})();

### ISSUE THREAD

**Issue by ocxers** [gruntjs/grunt-contrib-uglify#441]
When I try to ugly this function, `(function(){return function(a){console.log(a);}})();`
It returns the WRONG result: `!function(){return function(n){console.log(n)}}();`

The RIGHT one should be: `(function(){return function(n){console.log(n)}})();`

**Comment by XhmikosR** [comment]
Does this happen with the same options passed to uglify-js itself?

**Comment by XhmikosR** [comment]
Closing as an upstream issue. If you verify this only happens with grunt-contrib-uglify itself let me know.
