### ISSUE TITLE
Footer option with sourceMap

### ISSUE THREAD

**Issue by GMartigny** [gruntjs/grunt-contrib-uglify#442]
Hi,

Adding a footer when a sourceMap is asked will result of footer on "sourceMappingURL".

Example :

```
options: {
  sourceMap: true,
  footer: "Foo"
}
```

output => `//# sourceMappingURL=script.js.mapFoo`

**Comment by XhmikosR** [comment]
Is this still an issue? If so please try and provide a patch.

**Comment by GMartigny** [comment]
I just reproduce it in v2.2.0
I can make a PR, but I'm not sure how you want to address this.

**Comment by XhmikosR** [comment]
@vladikoff: do we close this? See also #467.

**Comment by alexlamsl** [comment]
FWIW, #472 `footer` is retained (and `compress_mangle_beautify` test still passes).

The option itself will probably not interact with `sourceMappingURL` regardless of whether there is a pending new line or not though, since it's effectively disabled the directive in question.
