### ISSUE TITLE
Some preserved comment blocks are stripped

### ISSUE THREAD

**Issue by louisameline** [gruntjs/grunt-contrib-uglify#451]
Hi and thanks for your work.

Some blocks are stripped even though they shouldn't be. I found out that it depended on what's coming after the block, which should not matter.

For example,
```
/**
 * Modernizr 2.7.1
 * @license MIT & BSD
 */
;window.Modernizr=[...]
```
is stripped, while this is not:
```
/**
 * Modernizr 2.7.1
 * @license MIT & BSD
 */
window.Modernizr=[...]
```
This is also stripped:
```
/** @preserve hello */
'use strict';
```
I'm on windows, using the latest version.
Thank you.

**Comment by XhmikosR** [comment]
I doubt this has anything to do with this plugin.
