### ISSUE TITLE
Uglify 2.8.x API update required for compress options `reduce_vars` and `passes` 

### ISSUE THREAD

**Issue by kzc** [gruntjs/grunt-contrib-uglify#455]
See: 

https://github.com/mishoo/UglifyJS2/issues/1516#issuecomment-283102405

https://github.com/mishoo/UglifyJS2/blob/16cd5d57a5cf7f5750104df0e5af246708fd493f/test/compress/reduce_vars.js#L352-L384

See also: Uglify API use in [`UglifyJS2.minify()`](https://github.com/mishoo/UglifyJS2/blob/cf0951f72635f898ef9dc98ced3c73a1c488cc17/tools/node.js#L123-L124) and the [`uglifyjs CLI`](https://github.com/mishoo/UglifyJS2/blob/cf0951f72635f898ef9dc98ced3c73a1c488cc17/bin/uglifyjs#L457).

**Comment by XhmikosR** [comment]
Thanks, @alexlamsl mentioned this in https://github.com/gruntjs/grunt-contrib-uglify/pull/453#issuecomment-283256043 so I applied it there.
