### ISSUE TITLE
¿The version 0.9.1 is failing?

### ISSUE THREAD

**Issue by thepianist2** [gruntjs/grunt-contrib-uglify#457]
Hi, i having problems with the version 0.9.1 not working correctly because the parser or compressor not have a good result, exactly the javascript is failing on execution.

**Comment by stegmanh** [comment]
Hey encountered this too. Not sure the root cause/exactly how this fixed it but once I fixed this to version 0.9.1 and fixed my package.json's reference to uglify-js to 2.4.23 it seemed to resolve the issue

**Comment by tristanpemble** [comment]
What version of UglifyJS did you pull in? We ran into issues with v2.8.8 that was released last night (around the time you posted this issue), and downgrading to v2.8.7 fixed it. I think this issue is related: https://github.com/mishoo/UglifyJS2/issues/1573

**Comment by XhmikosR** [comment]
This is an upstream issue. Clear your local node_modules and reinstall and report any issues upstream.
