### ISSUE TITLE
Class variable missing after minify js

### ISSUE THREAD

**Issue by shine-eglobeits** [gruntjs/grunt-contrib-uglify#458]
In the js file 
`var Translate=Class.create();Translate.prototype={initialize:function(a).....`

In minified version
`Class.create().prototype={initialize:function(a)`

Looks like var Translate missing on minified version

**Comment by Wohlie** [comment]
Hi,

see https://github.com/mishoo/UglifyJS2/issues/1605 for more information.

I think this issue here can be closed.
