### ISSUE TITLE
Embedded sourcemap option?

### ISSUE THREAD

**Issue by qfox** [gruntjs/grunt-contrib-uglify#461]
While Uglify supports embedding sourcemaps inline I can't seem to find a way to do it through this package?

Neither the option `sourceMapInline: true` nor `sourceMapStyle: "embed"` nor `sourceMapStyle: "inline"` will inline the sourcemap. An external map is always created. 

Am I overlooking something or is this simply not supported?

```
    uglify: {
      dbg: {
        options: {
          report: 'gzip', 
          sourceMap: true,
          //sourceMapStyle: 'link', // embed link inline
          sourceMapInline: true,
        },
        files: {
          'dist/output.js': ['build/input.js'],
        },
      },
```

**Comment by qfox** [comment]
Maybe it would be handy to have an option object that is passed on straight to uglifyjs? That way you don't have to update this package every time there's a new feature in uglify. Or if it exists please document it because I didn't see such option described :)

**Comment by alexlamsl** [comment]
With 3.x `options.sourceMap` is now (almost) directly passed onto `uglify-js`:

https://github.com/gruntjs/grunt-contrib-uglify/blob/755360bee66c9d5a43650be7e82a88d88fca293b/tasks/lib/uglify.js#L52
