### ISSUE TITLE
2.2.0: Banner does not show up

### ISSUE THREAD

**Issue by aaron-nance** [gruntjs/grunt-contrib-uglify#463]
The banner option is no longer working.

For example, if your config looks something like this: 

            uglify: {
                options: {
                    banner: "//Hi There"
                }
            }

You won't get a banner. This worked fine in 2.1.0.

**Comment by XhmikosR** [comment]
Tests are passing fine so we need more info.

**Comment by conceptualspace** [comment]
+1

mac os 10.12.3
node v7.7.3

```
options: {
	banner: "\\TEST",
	dead_code: true,
	unused: true,
	loops: true,
	conditionals: true,
	booleans: true,
	drop_console: true,
	screwIE8: true,
	sourceMap: true,
	sourceMapIn: function(path) {
		return path+".map";
	}
}
```

**Comment by conceptualspace** [comment]
just to be explicit: the banner string does not appear in the uglified js. confirmed working in 2.1.0 with same options

**Comment by XhmikosR** [comment]
I still don't see what's wrong. The only code change was 0f638cf45e07daa997ee9cbf782f1365400747ac

**Comment by conceptualspace** [comment]
maybe something in uglify 2.8

**Comment by XhmikosR** [comment]
@alexlamsl: any idea?

**Comment by alexlamsl** [comment]
@XhmikosR I don't see `banner` anywhere in `uglify-js`, not even for `2.7.5`

Did `grunt-contrib-uglify` convert `options.banner` to `options.output.preamble` but dropped it at some point?

OT: this workaround may be obsolete now https://github.com/gruntjs/grunt-contrib-uglify/blob/373626827003303a2ad77b8014608874fc153b9c/tasks/uglify.js#L174-L177

**Comment by XhmikosR** [comment]
uglify-js never had a banner option IIRC. We had that.

My question is if any recent changes changed the preamble behavior. If so, then the line you suggest might no longer be needed.

Or can this change cause this issue? https://github.com/gruntjs/grunt-contrib-uglify/commit/0f638cf45e07daa997ee9cbf782f1365400747ac#diff-afaf7edd36b493b2d939b60518620ec6R101

**Comment by alexlamsl** [comment]
> Or can this change cause this issue?  0f638cf #diff-afaf7edd36b493b2d939b60518620ec6R101

I don't think so, no.

I just went through https://github.com/gruntjs/grunt-contrib-uglify/blob/master/tasks/uglify.js and AFAICT `options.banner` doesn't get converted to `options.output.preamble`, so `uglify-js` simply won't act on it, not even back in `2.7.x`

**Comment by alexlamsl** [comment]
So the only reason why `banner` would stop working over here is if somebody specified `options.sourceMap`, which https://github.com/gruntjs/grunt-contrib-uglify/issues/463#issuecomment-290616440 does.

**Comment by XhmikosR** [comment]
```js 
   if (options.banner && options.sourceMap) {
      outputOptions.preamble = options.banner;
    }
```

It is converted in lib/uglify.js...

**Comment by alexlamsl** [comment]
Oh, I didn't read https://github.com/gruntjs/grunt-contrib-uglify/blob/master/tasks/lib/uglify.js - sorry about that.

Let me verify now and get back to you...

**Comment by XhmikosR** [comment]
Can you review https://github.com/gruntjs/grunt-contrib-uglify/compare/banner?

**Comment by alexlamsl** [comment]
> Can you review https://github.com/gruntjs/grunt-contrib-uglify/compare/banner?

LGTM

I have also identified https://github.com/mishoo/UglifyJS2/pull/1545 as the reason why `preamble` (alone) does not work - it was trying to fix bad interactions with `shebang` but ended up relying on its (or other comments') presence in order to function.

Will push a fix to `uglify-js` and publish shortly. Thanks for the heads up!

**Comment by XhmikosR** [comment]
Thanks! Please ping me when the new version is out so that I release a patch version here too.

**Comment by alexlamsl** [comment]
`uglify-js 2.8.20` is tagged, waiting for Travis CI to complete in ~10 minutes.

**Comment by XhmikosR** [comment]
Thanks, published a new patch version.

@conceptualspace @aaron-nance: please confirm it fixes your issue.

**Comment by conceptualspace** [comment]
👍 

confirmed working in 2.2.1. thanks for the super prompt fix!
