### ISSUE TITLE
SyntaxError: Unexpected token: name (promise).

### ISSUE THREAD

**Issue by alinleonard** [gruntjs/grunt-contrib-uglify#468]
When I try to use grunt-contrib-uglify I get at line

`let promise = $timeout();`

**error:**

`SyntaxError: Unexpected token: name (promise).`

**Comment by XhmikosR** [comment]
Upstream issue, doesn't support ES6.

**Comment by pflannery** [comment]
@XhmikosR is it not possible that `grunt-contrib-uglify` allows us to switch the require call between `uglify-js` and `uglify-es`?

They apparently have the same API so it would only be a matter of adding `"uglify-es": "mishoo/UglifyJS2#harmony-v3.0.14"` to the package.json and an extra option to choose between es5(default) or es2015.

**Comment by pflannery** [comment]
@XhmikosR or the other alternative could be to have `grunt-contrib-uglify@next` which just uses `uglify-es` instead

**Comment by pflannery** [comment]
@XhmikosR ignore the last comments now :).  I've discovered that there is a branch here that does already support the es2015 version.

So I'm now using https://github.com/gruntjs/grunt-contrib-uglify/tree/harmony

and this is my package dep entry

```json
"grunt-contrib-uglify": "gruntjs/grunt-contrib-uglify#harmony"
```

@alinleonard does that solve the problem for you?
