### ISSUE TITLE
Update to uglify-js 3.x

### ISSUE THREAD

**Issue by XhmikosR** [gruntjs/grunt-contrib-uglify#471]
@alexlamsl: there have been quite a few changes. Can you highlight the important ones or even better submit a PR? Thanks!

**Comment by alexlamsl** [comment]
The major one being `UglifyJS.minify()`, which is now the only way to perform compression.

I'll put together a PR for this project since it's probably easier this way. :wink:

**Comment by XhmikosR** [comment]
Thanks!

We are using `parse()` so I couldn't quickly figure out the needed changes.

**Comment by XhmikosR** [comment]
@vladikoff: might be worth giving @alexlamsl push rights to this repo, if he agrees of course :)

**Comment by vladikoff** [comment]
@XhmikosR @alexlamsl invited!
