### ISSUE TITLE
Unexpected token: keyword (const). on version 3.0.1

### ISSUE THREAD

**Issue by celsomtrindade** [gruntjs/grunt-contrib-uglify#477]
When using version `2.3.0` I could run the task when using code like this:

    const myValue = '123';

When upgrading to version `3.0.0` (or `3.0.1`) I now get an error of `Unexpected token: keyword (const).` . Is this an expected behavior or an error?

**Comment by alexlamsl** [comment]
This is related to `uglify-js` rather than `grunt-contrib-uglify`.

Long story short, `const` is an ES6 feature, and support in `uglify-js 2.x` has known issues, so it was removed in `uglify-js 3.x` as ES6 users should be using `uglify-es` instead.

**Comment by xosofox** [comment]
For those stumbling upon this and thinking... "And what should I do now?"

Do this:

```npm install grunt-contrib-uglify-es --save-dev```

**Comment by nise** [comment]
No good recommendation anymore: npm WARN deprecated grunt-contrib-uglify-es@3.3.0: deprecated

**Comment by nise** [comment]
You should go for terser: npm install grunt-terser --save-dev
