### ISSUE TITLE
Skipping bower_components...

### ISSUE THREAD

**Issue by sblantipodi** [gruntjs/grunt-contrib-uglify#478]
Hi,
I am trying to skip the minification of the bower_components folder, to do this I use:
```
src: [
                    	'!**/bower_components/**',
                        '**/*.html'
 ]
```

But it doesn't work, I tried pretty much all combinations but it doesn't work.
Is there a way to skip the minification of all the files inside this folder?

Thanks

**Comment by alexlamsl** [comment]
I'm not well-versed with the internals of `grunt`, but from https://gruntjs.com/configuring-tasks#files it implies `node-glob` is in use, and from https://github.com/isaacs/node-glob#glob-primer it says negation looks like `!(pattern|pattern|pattern)`, i.e. with a parenthesis around the pattern.

**Comment by sblantipodi** [comment]
I solved simply by switching the order 

`src: [                    	
                        '**/*.html',
                        '!**/bower_components/**'
 ]`

it seems that exclusions must be at the end

**Comment by alexlamsl** [comment]
Thanks for the information - good to know :+1:
