### ISSUE TITLE
How to remove the console logs in my minified/compresed js files using #Gruntfile.js?

### ISSUE THREAD

**Issue by gsivaprabu** [gruntjs/grunt-contrib-uglify#479]
Hi Experts,

Please help me, How to remove the console logs in my **minified/compresed** js files ? I have attached my grunt configuration file

Grunt file path:- 

[https://gist.github.com/gsivaprabu/c79681a742551e744ab27bb1281240c9](https://gist.github.com/gsivaprabu/c79681a742551e744ab27bb1281240c9)

**Comment by alexlamsl** [comment]
Try `drop_console` - https://github.com/mishoo/UglifyJS2#compress-options

**Comment by gsivaprabu** [comment]
Hi @alexlamsl  i am using that method but not removed any logs in  my souce.min.js file can u overwrite my Gruntfile where i added properly

Clone this [gist](https://gist.github.com/gsivaprabu/c79681a742551e744ab27bb1281240c9)

**Comment by alexlamsl** [comment]
I only know how to do it within `uglify-js`, no idea where to put that within `grunt`. Sorry.

**Comment by XhmikosR** [comment]
You are asking us to look at that huge gist and find a solution for you. The solution is what @alexlamsl said above; adapt it to your use case.
