### ISSUE TITLE
how concate multiple files to one desc file?

### ISSUE THREAD

**Issue by tlindig** [gruntjs/grunt-contrib-uglify#48]
if i do this:

```
var fileList = [ "js/file1.js", "js/file2.js", "js/file2.js" ];//will be generated
var buildDir = "build";
var distDir = "dist";

// Project configuration.
grunt.initConfig({
    uglify: {
        min: {
            files: [
                {
                    cwd: buildDir,
                    expand: true,
                    src: fileList,
                    dest: distDir + "/js/my.min.js"
                }
            ]
        }
    }
});
```

after grunt this, I got minified copies of every source file, in a directory "dist/js/my.min.js/".

But I want only one minified concatenation of the files. Is that a bug in the uglify task?

**Comment by front-end-developer** [comment]
I know this is late but for others out there to minifiy multiple files into one file do like:
uglify: {
        min: {
            files: [{
                    expand: true,
                    "path/to/output/filetominifyto.js": [
                     'filelist/directory/file1.js',
                     'filelist/directory/file2.js',
                     'filelist/directory/file3.js'
                  ]}
            ]
        }
    }

**Comment by wolfen351** [comment]
for those of you coming here looking for many to 1 file mapping, here is what worked for me:

```module.exports = function(grunt) {
    grunt.initConfig({
        uglify: {
            target1: {

                files: [
                    {
                        src: 'libs/**/*.js',
                        dest: 'obj/min.js'
                    }
                ]
            }
        }
    });
    grunt.registerTask('default', ['uglify:target1']);
    grunt.loadNpmTasks('grunt-contrib-uglify-es');
};```
