### ISSUE TITLE
Update uglify-es to the latest version on harmony branch to support async/await

### ISSUE THREAD

**Issue by adamtal3** [gruntjs/grunt-contrib-uglify#483]
The current version doesn't support `async/await` and updating to the latest version fixes that (`"uglify-es": "^3.0.24"`)

Thanks!

**Comment by alexlamsl** [comment]
@XhmikosR updating `harmony` branch after `uglify-js@3.1.0` is released on `master` should take care of this nicely.

**Comment by XhmikosR** [comment]
Thanks, I merged master into harmony.
