### ISSUE TITLE
sources and file properties in generated .map file are invalid

### ISSUE THREAD

**Issue by DamodarSojka** [gruntjs/grunt-contrib-uglify#486]
"grunt-contrib-uglify": "^0.7.0"
"grunt": "^0.4.5"

`uglify: {
            generated: {
                options: {
                    sourceMap: true
                }
            }
        },`

Generated .map file contains two invalid properties:
"file":"scripts.js","sources":["../../.tmp/concat/scripts/scripts.js"]

The name of the minified .js file is scripts.84bdfe65.js.

**Comment by XhmikosR** [comment]
You change the filename in a later step and it's impossible for the plugin to know that.

**Comment by DamodarSojka** [comment]
Is there a way to notify the plugin about it? Can you think of any workaround? I am quite sure I am not the only one having this use case so having a solid approach would increase the usability of the plugin.

**Comment by XhmikosR** [comment]
No way I'm aware of, sorry. You could hook up a replacement task somewhere in your pipeline though.
