### ISSUE TITLE
closing script tag (</SCRIPT>), is changed to lower case (<\/script>).

### ISSUE THREAD

**Issue by akgoyal1987** [gruntjs/grunt-contrib-uglify#488]
closing script tag (</SCRIPT>), is changed to lower case (<\\/script>) after running grunt uglify.
here is the code :

```
        var test = function (coId, calObj, dimId, isForAllMembers) {
            var xml = '';
            xml += '<SCRIPT>';
            xml += '<EXPRESSION>';
            xml += '<CALC_MEMS>';
            xml += '</CALC_MEMS>';
            xml += '</EXPRESSION>';
            xml += '</SCRIPT>';
            return xml;
        };
```
and the result is : 

```
var test=function(){var e="";return e+="<SCRIPT>",e+="<EXPRESSION>",e+="<CALC_MEMS>",e+="</CALC_MEMS>",e+="</EXPRESSION>",e+="<\/script>"};
```

here closing </SCRIPT> is changed to <\\/script>

this is causing error in XML parsing.

this is happening only with closing SCRIPT Tag.

Please provide solution for this problem.

Thanks :)
Ankit Goyal

**Comment by XhmikosR** [comment]
And what makes you think this isn't an upstream issue? Doesn't it happen with uglify itself?

**Comment by akgoyal1987** [comment]
@XhmikosR , it may be upstream issue, I didn't check, I accept that this is my fault. 
as I found this when I was uglifying my code using grunt-contrib-uglify, I reported it here. 
I will check this with uglify-js.

Thanks.

**Comment by alexlamsl** [comment]
@akgoyal1987 in case this may address your issue - `uglify-js` does `</script>` escaping if `inline_script` is enabled.

In the future please file the issue directly on https://github.com/mishoo/UglifyJS2/issues so I can notice it sooner.
