### ISSUE TITLE
How do I get the harmony branch , because when I do npm install grunt-contrib-uglify --save-dev its giving me uglify-js instead of uglify-es ?

### ISSUE THREAD

**Issue by sohansoni** [gruntjs/grunt-contrib-uglify#489]
How do I get the harmony branch , because when I do npm install grunt-contrib-uglify --save-dev its giving me uglify-js instead of uglify-es ?

**Comment by sohansoni** [comment]
Got it I did 
`npm install git://github.com/gruntjs/grunt-contrib-uglify.git#harmony `

**Comment by Qoraiche** [comment]
Install harmony branch in dev dependencies
`npm install git://github.com/gruntjs/grunt-contrib-uglify.git#harmony --save-dev`

**Comment by shawn-currey-usps** [comment]
too bad public key is blocked, is this still valid?

**Comment by shawn-currey-usps** [comment]
is this still valid? its gibing ssh and public key issues
