### ISSUE TITLE
Not support ES6 ES6, like let

### ISSUE THREAD

**Issue by chsyzxcv** [gruntjs/grunt-contrib-uglify#491]
Not ES6, like let in latest version ? grunt-contrib-uglify report Unexpected token name «subitem»
for example, for(let subitem in setting)

**Comment by XhmikosR** [comment]
https://github.com/gruntjs/grunt-contrib-uglify/issues/482#issuecomment-312860523

**Comment by alexlamsl** [comment]
Use `harmony` branch which supports up to ES8.

**Comment by chsyzxcv** [comment]
hi alexlamsl , how can we install harmony branch by using npm?
npm install grunt-contrib-uglify --save-dev

**Comment by chsyzxcv** [comment]
hi alexlamsl,
i had successfully install harmony version . It's work perfectly. Thank you so much
npm install git://github.com/gruntjs/grunt-contrib-uglify.git#harmony
