### ISSUE TITLE
3.1.0 Release didn't actually bump uglify-js dependency?

### ISSUE THREAD

**Issue by brianjmiller** [gruntjs/grunt-contrib-uglify#492]
The 3.1.0 release indicates it bumps uglify-js to 3.1.0 but the dependency in the `package.json` itself doesn't appear to be updated.

https://github.com/gruntjs/grunt-contrib-uglify/blob/master/package.json#L21

**Comment by alexlamsl** [comment]
Thanks for spotting this - fixed!
