### ISSUE TITLE
sourceMap.includeSources not working

### ISSUE THREAD

**Issue by jlobello** [gruntjs/grunt-contrib-uglify#493]
I would like the source maps to also include the source code, but haven't been able to do that. It looks like grunt-contib-uglify is not passing the option onto uglify. Here are the options I'm using...

```js
uglify: {
    options: {
        compress: {
            unused: false
        },
        preserveComments: "some",
sourceMap: function(path) {
          return path + ".map";
        },
sourceMapIncludeSources: true,
        beautify: {
            beautify: false,
            ascii_only: true
        }
    },
    dynamic_mappingsLower: {
        files: [{
            expand: true, // Enable dynamic expansion.
            cwd: "<%= dir.main %>/static/", // Src matches are relative to this path.
            src: ["IccControls/**/*.js",
                "js/**/*.js",
                "sframe/*.js",
                "squid/**/*.js",
                "!sframe/sframeCommonLogon.js"
            ], // Actual pattern(s) to match.
            dest: "<%= dir.dist %>/static/", // Destination path prefix.
            ext: ".js", // Dest filepaths will have this extension.
        }, ],
    },
```

**Comment by XhmikosR** [comment]
You are doing it wrong. Please read the upstream docs.

**Comment by jlobello** [comment]
I looked at some of your unit tests & fixed my issue.  I was adding this to the global uglify options, but that didn't work.  I had to add it to the file portion...

        uglify: {
            options: {
                compress: {
                    unused: false
                },
                preserveComments: "some",
				sourceMap: function(path) {
                  return path + ".map";
                },
                beautify: {
                    ascii_only: true
                }
            },
            dynamic_mappings: {
                // Grunt will search for "**/*.js" under "lib/" when the "uglify" task
                // runs and build the appropriate src-dest file mappings then, so you
                // don't need to update the Gruntfile when files are added or removed.
                files: [{
                    expand: true, // Enable dynamic expansion.
                    cwd: "<%= dir.main %>/static/", // Src matches are relative to this path.
                    src: ["IccControls/**/*.js",
                        "IccControls/**/*.JS",
                        "js/**/*.js",
                        "js/**/*.JS",
                        "sframe/*.js",
                        "squid/**/*.js",
                        "!sframe/sframeCommonLogon.js"
                    ], // Actual pattern(s) to match.
                    dest: "<%= dir.dist %>/static/", // Destination path prefix.
                    ext: "", // Dest filepaths will have this extension.
                }, ],
                options: {
                  sourceMap: {
                   includeSources: true
                 }
               },
            },
