### ISSUE TITLE
Support the new uglify es6

### ISSUE THREAD

**Issue by GMartigny** [gruntjs/grunt-contrib-uglify#494]
Hello,

The uglify repository deploy the "harmony" branch into npm under the [uglify-es](https://www.npmjs.com/package/uglify-es) package. This version support all the new ES6 synthax.

Do you plan to move to this version ? Or should it be a new plugin ?
According to the README, uglify-es is compatible with uglify-js@3.

Thanks for all the good work.

**Comment by alexlamsl** [comment]
https://github.com/gruntjs/grunt-contrib-uglify/issues/482#issuecomment-312860523
