### ISSUE TITLE
How to create many individual uglify tasks in grunt?

### ISSUE THREAD

**Issue by TheNexusDesigns** [gruntjs/grunt-contrib-uglify#500]
Hey, when I try to create many uglify tasks I get errors. I have to comment and uncomment one task in order to get one task working correctly. Hope someone can help me. I need two sperate minified .js files created using this plugin but I can't figure it out. if it's possible to create both tasks in one task command that would create two sperate minified .js files like below that would be also great. Looking forward to ideas, please.

```js
module.exports = function(grunt){

	grunt.loadNpmTasks('grunt-contrib-uglify');
	
		grunt.initConfig({
		pkg: grunt.file.readJSON('package.json'),
		uglify:{
			t1:{
				files:{
					'build/scripts1.js' : ['abc.js', 'xc.js' ]

				}
			}
		},

		uglify:{
			t2:{
				files:{
					'build/scripts2.js' : ['123.js', 63a5.js]

				}
			}
		}
		});
};
```

**Comment by XhmikosR** [comment]
Because you are doing wrong. You don't need two `uglify` tasks; you need one with two targets.
