### ISSUE TITLE
message: 'Unexpected token operator «=» error when using default values for variables in a javascript function.

### ISSUE THREAD

**Issue by shawnCaza** [gruntjs/grunt-contrib-uglify#501]
The message I receive is:

>  message: 'Unexpected token operator «=», expected punc «,»',

The line of code that is causing the trouble:

`function update_filter_ui(type='all')`

I just added in the type='all' variable default to this function. Everything went fine with uglifying my .js files before this.

**Comment by alexlamsl** [comment]
Works fine in `uglify-es`
