### ISSUE TITLE
Can't npm install grunt-contrib-uglify-es - Error 404

### ISSUE THREAD

**Issue by doronoded** [gruntjs/grunt-contrib-uglify#506]
I get npm install error when trying to install grunt-contrib-uglify-ex:

```
npm ERR! code E404
npm ERR! 404 Not Found: grunt-contrib-uglify-es@latest
```

**Comment by alexlamsl** [comment]
https://github.com/gruntjs/grunt-contrib-uglify/issues/499#issuecomment-354288623
