### ISSUE TITLE
Error parsing Async function

### ISSUE THREAD

**Issue by PaulB2Code** [gruntjs/grunt-contrib-uglify#511]
Hi, 

I get an issue: 

Warning: Uglification failed.
Unexpected token keyword «function», expected punc «,». 
Line 120886 in .build/js/app5.js
 Use --force to continue.

 120886   componentDidMount: async function componentDidMount() {

Does somehow have an idea how I could manage this issue?

**Comment by alexlamsl** [comment]
Follow the template at https://github.com/mishoo/UglifyJS2/issues and file there.
