### ISSUE TITLE
uglify SntaxError (Unexpected token)

### ISSUE THREAD

**Issue by ActiDev** [gruntjs/grunt-contrib-uglify#512]
Hi!

I concat all my JS of my Angular JS app in the same file (.tmp/concat/scripts/scripts.js) and now I want to uglify it but i have this error:

> Warning: Uglification failed.
> SyntaxError: Unexpected token: name (Object).
> Line 1860 in .tmp/concat/scripts/scripts.js

The line 1860 is
`$state.go($rootScope.originState.name, { [Object.keys($rootScope.originState.params)[0]]: $rootScope.originState.params[Object.keys($rootScope.originState.params)[0]] });`

After some search on the Internet i try to use babel before uglify but i have the same issue.
It seems like the brace [ ... ] around "Object.keys($rootScope.originState.params)[0]" is the problem. How can I solve it ?

Please can you help me ?

**Comment by alexlamsl** [comment]
Follow the template at https://github.com/mishoo/UglifyJS2/issues and file there.
