### ISSUE TITLE
Unexpected token error with no information

### ISSUE THREAD

**Issue by wemmick** [gruntjs/grunt-contrib-uglify#513]
I'm running the latest Uglify gem with Rails 4.2 (using ```bundle exec rake assets:precompile RAILS_ENV=production```), and it chugs through a lot of my files, but errors out with:

```rake aborted!
Uglifier::Error: Unexpected token: eof (undefined)
/Users/me/.rvm/gems/ruby-2.4.2/gems/uglifier-4.1.5/lib/uglifier.rb:234:in `parse_result' 
```

Is there some way I can get more information about which file it's erroring out on?  I'm not quite sure where to start looking.  Thanks for any help!

For reference, this is the line I use in ```production.rb```:
```
config.assets.js_compressor = Uglifier.new(:harmony => true, :parse => { :bare_returns => true } )
```

**Comment by alexlamsl** [comment]
Your runtime environment is discarding useful information from `SyntaxError` - nothing we can do here.
