### ISSUE TITLE
SourceMap issue

### ISSUE THREAD

**Issue by MohitTilwani15** [gruntjs/grunt-contrib-uglify#514]
Hey All,
As you can see from the below screenshot, all my console logs points to one file, even though the logs are from other files. Any Idea what can be issue?
<img width="167" alt="screen shot 2018-02-05 at 13 21 58" src="https://user-images.githubusercontent.com/13518712/35804369-dadf61c8-0a77-11e8-99e9-b952b022ba44.png">

**Comment by alexlamsl** [comment]
Follow the template at https://github.com/mishoo/UglifyJS2/issues and file there.
