### ISSUE TITLE
Npm install gives error "Unhandled rejection Error: Command failed: /usr/bin/git checkout  c2ccee1b61a585c5f4fca00da8f79cc1db37048b fatal: reference is not a tree: "

### ISSUE THREAD

**Issue by MiodragL** [gruntjs/grunt-contrib-uglify#521]
I am trying to build mine css js files with Grunt, but when i run **npm install**, it gives me error:

Unhandled rejection Error: Command failed: /usr/bin/git checkout c2ccee1b61a585c5f4fca00da8f79cc1db37048b
fatal: reference is not a tree: **c2ccee1b61a585c5f4fca00da8f79cc1db37048b**

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

When i looked in my package-lock.json file this reference **c2ccee1b61a585c5f4fca00da8f79cc1db37048b** is reffered to UglifyJs.

Anyone has idea?

Thanks!

**Comment by agnaveen** [comment]
any help to fix this issue, I am facing the same issue......

**Comment by XhmikosR** [comment]
uglify-es is deprecated.
