### ISSUE TITLE
 New dependency name: uglify-es => terser #1 

### ISSUE THREAD

**Issue by fabiosantoscode** [gruntjs/grunt-contrib-uglify#522]
There has been development on a new fork of uglify-es, which is now called terser and has its own package!

    "terser": "^3.7.3"

Please upgrade to our new version.

**Comment by alexlamsl** [comment]
This package uses `uglify-js`, thank you.

**Comment by bricss** [comment]
Interesting, what if I want to minify es6+ code? 🤔

**Comment by bricss** [comment]
For those who wanna minify ES6+:
```javascript
const options = {
  compress: {
    passes: 3,
  },
  ecma: 8,
  output: {
    beautify: false,
  },
  toplevel: true,
};
```
```javascript
terser: {
  main: {
    files: [
      {
        cwd: '<%= meta.rootPath %><%= meta.srcPath %>/js/',
        dest: '<%= meta.assyPath %><%= meta.srcPath %>/js/',
        expand: true,
        src: ['*.js'],
      },
    ],
  },
  options,
},
```
```javascript
grunt.registerMultiTask('terser', 'Parse, mangle & compress source code files.', function () {
  this.files.forEach((file) => {
    let contents = grunt.file.read(file.src);
    contents = terser.minify(contents, this.options()).code;
    grunt.file.write(file.dest, contents);
  });
});
```
```javascript
grunt.registerTask('minify', ['terser']);
```
Just add it to your `gruntfile.js` and change paths for your files.

**Comment by fcamblor** [comment]
> ```
> grunt.registerMultiTask('terser', 'Parse, mangle & compress source code files.', function () {
>   this.files.forEach((file) => {
>      let contents = grunt.file.read(file.src);
>      contents = terser.minify(contents, this.options()).code;
>      grunt.file.write(file.dest, contents);
>    });
> });
> ```

For the record, now that `terser` is performing `minify()` asynchronously, I had to adapt a little bit the task to :
```
    grunt.registerMultiTask('terser', 'Parse, mangle & compress source code files.', function () {
        var done = this.async();
        Promise.all(this.files.map((file) => {
            return new Promise((resolve, reject) => {
                let contents = grunt.file.read(file.src);
                terser.minify(contents, this.options()).then((result) => {
                    grunt.file.write(file.dest, result.code);
                    resolve();
                }, reject);
            });
        })).then(done, (error) => { console.error(error); done(); });
    });
```

**Comment by fabiosantoscode** [comment]
@fcamblor sorry about that change, I needed to update source-map which is now async.

I'd like to make clear, though, that this didn't make terser concurrent. I'm experimenting with ways to do it using workers right now but it will be a while before I finish.

**Comment by fcamblor** [comment]
@fabiosantoscode don't apologize ! :-)
Thanks to you and @bricss I was able to workaround my issue of having a new ES2015 lib dependency in my non-ES2015 project without changing a lot of things in my build.

All of this in 1-2h thanks to `terser` 🙏
