### ISSUE TITLE
grunt-contrib-uglify-es v3.4.0 is not on NPM

### ISSUE THREAD

**Issue by jaller94** [gruntjs/grunt-contrib-uglify#528]
Can you please also update the project in the NPM directory?
Is there a testing period?

Best
Jaller

**Comment by jaller94** [comment]
I just noticed that this might not be the repo for `grunt-contrib-uglify-es`.

The page of it links to this repo:
https://www.npmjs.com/package/grunt-contrib-uglify-es

**Comment by alexlamsl** [comment]
There is no `uglify-es@3.4`, therefore no won't be any updates to `grunt-contrib-uglify-es`
