### ISSUE TITLE
uglification failed unexpected token operator during grunt build

### ISSUE THREAD

**Issue by ShobhaPatwal** [gruntjs/grunt-contrib-uglify#539]
Uglification failed warning is coming when grunt build. It is showing the error in temp file for vendor.js  file.
![error](https://user-images.githubusercontent.com/50516339/57568206-b3b0ab80-7401-11e9-8431-b583c04a19d3.PNG)
![error1](https://user-images.githubusercontent.com/50516339/57568207-b3b0ab80-7401-11e9-9671-d3fd5e9ba02a.PNG)

**Comment by alexlamsl** [comment]
You will need to provide said `vendor.js` in order for any progress to be made about your issue.

**Comment by alexlamsl** [comment]
Please file a report at https://github.com/mishoo/UglifyJS2/issues and follow the instructions there.
