### ISSUE TITLE
Why is grunt-contrib-uglify-es deprecated?

### ISSUE THREAD

**Issue by happypoulp** [gruntjs/grunt-contrib-uglify#541]
Hi,

I am trying to have uglify support `async / await` syntax and it looks like I should use `uglify-es` for that. However I am using grunt and it looks like I must use `grunt-contrib-uglify-es` to be able to use `uglify-es` in grunt.

How does it come that `grunt-contrib-uglify-es` is deprecated if it's the only way to use `uglify-es` in grunt? (in npm at least it is displayed as being deprecated: https://www.npmjs.com/package/grunt-contrib-uglify-es)

![deprecated module](https://user-images.githubusercontent.com/100044/59038207-f041bc80-8872-11e9-9ae0-29a856afefc2.png)

Is there any way to have uglify support `async / await` syntax in grunt without using `grunt-contrib-uglify-es`?

Thanks a lot for your insights!

**Comment by fyrye** [comment]
Most likely because [uglify-es has been depreciated](https://github.com/mishoo/UglifyJS2/issues/3156). 

The community seems to be migrating to [terser-js/terser](https://github.com/terser-js/terser), which is a fork of uglify-es.

**Comment by happypoulp** [comment]
I understand, thanks a lot for your help!
