### ISSUE TITLE
When and if the harmony branch will be merged ?

### ISSUE THREAD

**Issue by dan-menkes** [gruntjs/grunt-contrib-uglify#547]
I am trying to run a grunt task with es2016 code and grunt-contrib-uglify which does not work.
In this blog - https://davidburgos.blog/how-to-fix-grunt-contrib-uglify-for-es6/ the harmony branch is mentioned as a solution.
I was wandering if there are any plans to merge his branch back to the maim projects ?

**Comment by alexlamsl** [comment]
`grunt-contrib-uglify-es` is published and available on `npm` public registry, so you can just import it directly without using that branch trick described in that link.
