### ISSUE TITLE
Has grunt-contrib-uglify started supporting ES6?

### ISSUE THREAD

**Issue by Hlsgs** [gruntjs/grunt-contrib-uglify#555]
I remember getting errors a while back when I had any ES6 code, but it now seems to work. Have you added ES6 support?

**Comment by alexlamsl** [comment]
Yes &minus; `uglify-js` now have better support for ECMAScript than `uglify-es`

If you encounter any issues with your input code please [file a report with `uglify-js`](https://github.com/mishoo/UglifyJS/issues/new?assignees=&labels=&template=bug_report.md&title=)

**Comment by Hlsgs** [comment]
> 
> 
> Yes − `uglify-js` now have better support for ECMAScript than `uglify-es`
> 
> If you encounter any issues with your input code please [file a report with `uglify-js`](https://github.com/mishoo/UglifyJS/issues/new?assignees=&labels=&template=bug_report.md&title=)

That's awesome! Wasn't really looking forward to migrate away from `grunt-contrib-uglify` just beacause of the odd arrow function. Thanks for taking the time to answer.
