### ISSUE TITLE
Issue with grunt as dev dependency

### ISSUE THREAD

**Issue by hemachandsai** [gruntjs/grunt-contrib-uglify#559]
Shouldn't grunt be a direct dependency in this plugin turning grunt into a peer dependency for projects installing this plugin?

**Comment by XhmikosR** [comment]
Nope, that's exactly the opposite of how peer dependencies work.

**Comment by hemachandsai** [comment]
Thanks for the reply, is is that grunt is a peer dependency for the project but peer dependency installation is handled by npm and we need not add it as direct dependency. If it was any other package related to functionality it should have been included as direct dependency right? because of the fact that grunt is only required during the package build time and not during the server runtime.
