### ISSUE TITLE
Add documentation for reserveDOMCache option

### ISSUE THREAD

**Issue by evilaliv3** [gruntjs/grunt-contrib-uglify#565]
By looking at the default options recommended i've found the reserveDOMCache option and i just noticed that it is not documented.

This ticket is to kindly ask for a clarification about this functionality and when it is recommended to enable it so that we could work on improving the documentation: https://github.com/gruntjs/grunt-contrib-uglify/blob/main/docs/uglify-options.md

Thank you!

**Comment by alexlamsl** [comment]
I believe that's a typo &minus; it should be `reserveDOMProperties`:
https://github.com/gruntjs/grunt-contrib-uglify/blob/v5.1.0/README.md#reservedomproperties

Feel free to submit a Pull Request to fix the documentation.
