### ISSUE TITLE
Getting error when using optinal chaining

### ISSUE THREAD

**Issue by prashantkapate** [gruntjs/grunt-contrib-uglify#583]
We are getting an error when using optional chaining

 Error: Line 107: Unexpected token.
 Modules we are using as below with node 16
 "dependencies": {
    "grunt": "^1.4.1",
    "grunt-contrib-requirejs": "^1.0.0",
    "grunt-text-replace": "^0.4.0"
  },
  "devDependencies": {
    "grunt-cli": "^1.4.3",
    "grunt-contrib-concat": "^1.0.1",
    "grunt-contrib-copy": "^1.0.0",
    "grunt-contrib-cssmin": "^2.2.1",
    "grunt-contrib-uglify": "^5.2.2",
    "postcss": "^8.4.13",
    "postcss-cli": "^9.1.0",
    "postcss-import": "^14.1.0"
  }

**Comment by alexlamsl** [comment]
Please file the report with [`uglify-js`](https://github.com/mishoo/UglifyJS/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=) by following the instructions there, e.g. provide the input that reproduce the issue etc.
