### ISSUE TITLE
Setting 'compress' option to 'false' still results in minified output.

### ISSUE THREAD

**Issue by necolas** [gruntjs/grunt-contrib-uglify#65]
According to my reading of the UglifyJS docs, you should be able to disable all compression, but I couldn't do this with the latest release of this task.

**Comment by FrankFan** [comment]
```javascript
// 是否压缩代码
output: {
    beautify: false
}
```

**Comment by AntonioRedondo** [comment]
Why this issue has been closed without being solved? As of February 2016 (v0.11.1) `compress: false` still doesn't work. I had to resort to the `concat` task to solve the problem. `beautify: true` still modifies the original source.

**Comment by UltCombo** [comment]
According to a [comment above](https://github.com/gruntjs/grunt-contrib-uglify/issues/65#issuecomment-19563417), the same problem occurs when using uglify directly. This repository is a small wrapper around the [UglifyJS2](https://github.com/mishoo/UglifyJS2) package, so this issue should be reported there if it hasn't been already.

**Comment by frankie-loves-jesus** [comment]
Same problem here :/

**Comment by MikeGodin** [comment]
Setting beautify to true seems to allow mangle and compress to be set to false.

       options : {
          beautify: true,
          mangle : false, 
          compress : false 
        },

**Comment by Cerberooo** [comment]
For those who wonder why @MikeGodin's answer doesn't work, it's
```javascript
options : {
      output { beautify: true },
      mangle : false, 
      compress : false 
}
```
now.

**Comment by b3wii** [comment]
> 
> 
> For those who wonder why @MikeGodin's answer doesn't work, it's
> 
> ```js
> options : {
>       output: { beautify: true },
>       mangle : false, 
>       compress : false 
> }
> ```
> 
> now.
