### ISSUE TITLE
Sourcemaps fail if the output file is not located in the project root directory

### ISSUE THREAD

**Issue by bill-barron** [gruntjs/grunt-contrib-uglify#71]
Source maps fail when
- Source files are specified with relative paths (js/source)
- Destination files are not in the project root directory (js/build)
- Source map files are not placed in the project root directory (js/build)

Browsers look for the source map file in the destination file. The path in the destination file is considered relative to the destination file, not the web root.

If the source map file is found, the file it refers to is considered relative to the source map file not the web root.

So in the following scenario, the browser looks for the source file in /js/build/js/source

One workaround is to place the source map files in the project root and place both the destination and source files in js/build/ then make sure the sourceMappingURL starts with "../../"

== Ideal ==

```
        uglify: {
            options: {
                sourceMap: '<% filename %>.map',
                sourceMapRoot: 'http://localhost/',
                banner: '/*! <%= grunt.template.today("yyyy-mm-dd") %> */\n'
            },
            vendor: {
                src: 'js/build/vendor.js',
                dest: 'js/build/vendor.min.js'
            },
            home: {
                src: 'js/build/home.js',
                dest: 'js/buildhome.min.js'
            }
        }
```

== Workaround ==
Source maps must be placed in the root directory

```
        uglify: {
            options: {
                sourceMap: function (path) {
                    return path.replace(/js\/build\/(.*).min.js/, "$1.map.js");
                },
                sourceMappingURL: function (path) {
                    return path.replace(/js\/build\/(.*).min.js/, "../../$1.map.js");
                },
                sourceMapRoot: 'http://localhost/',
                banner: '/*! <%= grunt.template.today("yyyy-mm-dd") %> */\n'
            },
            vendor: {
                src: 'js/build/vendor.js',
                dest: 'js/build/vendor.min.js'
            },
            home: {
                src: 'js/build/home.js',
                dest: 'js/buildhome.min.js'
            }
        }
```

**Comment by light24bulbs** [comment]
And there's no good explanation of what this does in the docs, that I saw.
